### ISSUE TITLE
As a user, I want to execute content validation against every nth file

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#1]
This ticket is phase 2 of the data spot checking capability discussed at one of the Tool Working Group meetings back in Sept 2018. Phase 1 (PDS-603) dealt with spot checking every nth record (or line for arrays).

This ticket will deal with adding the capability to spot check every nth file. A new command-line flag option should be added to enable this feature and it can be used in combination with the <i>--spot-check-data</i> flag, which tells the tool to skip every nth record.

For example this ticket would implement a flag like:
`--everyN`

e.g.
`--everyN 10`

This is a temporary improvement to the performance upgrade requirement.

## Engineering Details
* Validate should still check all labels and perform all other integrity checking as expected
* However, it should only check the content of every N product

**Comment by jordanpadams** [comment]
@danyu-pds you can find test data at `pds-gamma:$TEST_HOME/software/validatePDS-603`. I will Slack you the $TEST_HOME path

**Comment by mcayanan** [comment]
@danyu-pds You can also find test data on the PDS home page:
`https://pds.nasa.gov/datastandards/documents/examples/`
The package referenced at the top of this page, 1.9.0.0, has a zip file which you can download. It contains an example bundle and a set of example products you could use in your test as well.

**Comment by danyu-pds** [comment]
> @danyu-pds You can also find test data on the PDS home page:
> `https://pds.nasa.gov/datastandards/documents/examples/`
> The package referenced at the top of this page, 1.9.0.0, has a zip file which you can download. It contains an example bundle and a set of example products you could use in your test as well.

@mcayanan Thanks!

**Comment by mdrum** [comment]
This issue is becoming a major hinderance for us again @jordanpadams. Just a heads up, I know we'll have a chance to prioritize soon, but just wanted to raise the issue here.

**Comment by jordanpadams** [comment]
@mdrum i heard from SBN-UMD folks as well. have you tried using validate-bundle to parallelize the execution? See "Using validate-bundle parallelization" under https://nasa-pds.github.io/validate/operate/index.html#Advanced_Bundle_Validation

**Comment by mdrum** [comment]
> have you tried using validate-bundle to parallelize the execution?

Yes, that helped out on our end a bit. I just spoke with UMD who brought this issue to us, so I'm kinda advocating for them here too. We are gonna do some number crunching and get you some actual metrics, but we are more likely needing something like a 1000x performance improvement for data validation, rather than an 8x that we'd get from parallelizing, to have feasible validation runs of surveys that don't take months.

**Comment by jordanpadams** [comment]
@mdrum copy.

We should maybe have a sit-down about the architecture being used here too. There are numerous options to improve the performance like.
1. moving content validation closer to the data generation - generate product/label, perform content validation, then perform bundle validation at the end to do all the integrity checking
2. Use a script to create a manifest of every nth file, run validate with content validation with that manifest, run validate with content validation disabled for the rest of the bundle
3. Do number 2 above to gain enough confidence the archive is valid, release the data, run validate with content validation on every product once it's online just to make sure it's all good. (Would probably recommend this for any spot checking use)

**Comment by jordanpadams** [comment]
@al-niessner the stakeholders who wanted this requirement no longer have a need. Going to discuss with SWG, but plan to descope this from current implementation. Will also close PR, but we will leave the branch out there in case we revisit.

**Comment by jordanpadams** [comment]
@al-niessner nevermind. SBN-UMD says they need this, so still in the plans for this Build.

**Comment by jimmie** [comment]
effort a bit derailed due to investigating poor performance

**Comment by tloubrieu-jpl** [comment]
performance understood.

**Comment by miguelp1986** [comment]
@jordanpadams @al-niessner,

I ran the following test along with some of my own tests and I'm getting unexpected results:

From https://github.com/NASA-PDS/validate/pull/587, here is a test and the expected result:

```
validate --everyN 2 src/test/resources/github531/success/b.xml src/test/resources/github531/fail/b.xml src/test/resources/github531/success/b.xml src/test/resources/github531/fail/b.xml

  Product Validation Summary:
    2          product(s) passed
    0          product(s) failed
    0          product(s) skipped
```


Here is my result :
```
Summary:

  2 error(s)
  0 warning(s)

  Product Validation Summary:
    2          product(s) passed
    2          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    2            error.label.table_definition_problem
```
It looks like `--everyN 2` isn't being picked up. I am using  version 3.2.0-SNAPSHOT:
```
validate --version                                                                                                                                    ─╯

gov.nasa.pds:validate
Version 3.2.0-SNAPSHOT
Release Date: 2023-03-22 15:19:08

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
```

I've attached my full output.
[output.txt](https://github.com/NASA-PDS/validate/files/11166434/output.txt)

**Comment by jordanpadams** [comment]
@miguelp1986 per discussions above, I think this is expected. It validates the metadata labels of all 4 products, but only checks the content of 2 of them. I would test with all 4 products failing with content bugs, but it only catches 2 because we skipped the other 2. If that makes sense?

**Comment by Yeqzids** [comment]
Hi all. I am running this on a large dataset (~1700 files) and there is something that I don't understand. I'd expect that --everyN will run faster since it only checks the content for the Nth file. However, for my case the test with --everyN and the one that without takes roughly the same amount of time to run (in my case, about 3 hours, with a difference of about 10 seconds). Is this expected? I am using 3.2.0 and a large everyN (100).
