### ISSUE TITLE
Registered context product resource lists only one of multiple instrument or target multiple types

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#107]
**Describe the bug**
Both instrument and target context products can have >1 type attributes, which are not currently reflected in the registered context product resource.

**Version of Software Used**
1.16.0-SNAPSHOT (rc1)

**Additional context**
The problem was encountered trying to create a local context product resource for instruments with multiple types.

**Comment by msbentley** [comment]
I checked in the currently registered context products and there are 13 with >1 type attributes (all instruments, as it happens). As a concrete example:

[urn:nasa:pds:context:instrument:dawn.vir::1.0](https://starbase.jpl.nasa.gov/pds4/context-pds4/instrument/dawn.vir_1.0.xml)

has:

```xml
<Instrument>
    <name>VISIBLE AND INFRARED SPECTROMETER</name>
    <type>Imager</type>
    <type>Spectrometer</type>
```

and in the registered context product resource json only the first  appears:

```json
  {
       "name": "VISIBLE AND INFRARED SPECTROMETER",
       "type": "IMAGER",
       "lidvid": "urn:nasa:pds:context:instrument:dawn.vir::1.0"
  },
```

**Comment by msbentley** [comment]
Hi @jordanpadams I'm still seeing some odd behaviour in the release of yesterday - it looks like the value in my label is being compared to the json array as a string or similar:

```java
WARNING  [warning.label.context_ref_mismatch]   line 71: Context reference name mismatch. Value: 'SOLAR_WIND' Expected one of: '[SOLAR WIND]'
```

**Comment by jordanpadams** [comment]
@msbentley that's actually a valid warning message. The value in your label has an underscore in it, while the context product value has a space.

**Comment by msbentley** [comment]
D'oh, you are of course totally right, my bad! Apparently I'm blind to underscores...sorry!

**Comment by jordanpadams** [comment]
Staring at XML all day has that effect.
