### ISSUE TITLE
Performance degradation on Windows c.f. linux/mac

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#114]
**Describe the bug**
Performance of validate on WIndows is an order of magnitude worse than linux/mac. As an example, we profiled a few products (~650 MB in total) and on linux validation takes 5 minutes. On Windows, it took longer than one hour.

**Version of Software Used**
Tested with validate 1.14 and 1.15.3 with similar results

**Desktop (please complete the following information):**
ubuntu 18.04 and Windows 7

**Additional context**
If there are any configuration tweaks to be tested, or information about the systems needed, please let me know!

**Comment by jordanpadams** [comment]
@msbentley i would be interested to see if this would be fixed with 1.16.0 . We just made a major update to the way Validate handles content validation, so hopefully this will be resolved. if not, we will need to do more testing on Windows.

**Comment by msbentley** [comment]
HI @jordanpadams - interesting! The 2019-09-26 snapshot indeed dramatically improves performance - in particular on Windows. The test case above runs in 2m30s on linux (2x improvement), and 5m on Windows (12x improvement!). I'll get our "real Windows" users to test as well, but it looks good - thanks!

**Comment by msbentley** [comment]
Just to confirm, a "real" Windows user also sees these dramatic performance improvements!

**Comment by jordanpadams** [comment]
@msbentley you mind sending over the number of files, average size, and the runtime for these performance improvements? we would like to start capturing some of these benchmarks
