### ISSUE TITLE
Enhance validate performance to average <1 second with content validation enabled

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#123]
`L5.PRP.VA.43	The tool shall average less than 1 second execution time per 100MiB when content validation is enabled.`

Our current benchmarks (see below) still take 10 minutes for large files (GBs) and 4-8 seconds for smaller files (MBs). This is a significant improvement from before, but deliveries involve thousands of products, so validate is still taking days instead of hours to run on one delivery. We need to figure out where else we can improve performance.

This Epic includes all tasks separate specific to improving content validation.

Large test data sets are on `pds-dev-el7:/path/to/test/data/insight_cameras`

<img width="843" alt="Screen Shot 2019-10-04 at 9 37 00 AM" src="https://user-images.githubusercontent.com/33492486/66224621-3543f700-e68b-11e9-8737-5fe30770e3ef.png">

NOTE: You may need to execute with a catalog file or against multiple products to see improved performance. The initial loading of schemas/going out to internet will always take some time.

**Comment by msbentley** [comment]
Hi @jordanpadams - are the performance limits reached in validate, or is there still scope for more? With validate 1.20.0 it still takes ~60 seconds for a 170 MB table, for example

**Comment by jordanpadams** [comment]
@msbentley unfortunately, this is all we could determine could be done to improve performance without a complete refactor of the software (or even re-implementation in another programming language). the biggest bottleneck is the Java XML libraries are not thread-safe, so we can't parallelize within the java code.

we do have a [shell script merged into the source](https://github.com/NASA-PDS-Incubator/validate/blob/master/src/main/resources/bin/validate-bundle) for bundle validation that we want to go through I&T before we deploy to operations to ensure it works as expected.

sorry for the inconvenience.

**Comment by msbentley** [comment]
Thanks @jordanpadams, it was just to know what to expect, so we can plan how best we do validation.
