### ISSUE TITLE
L5.PRP.VA.42	The tool shall average less than 1 second execution time when content validation is disabled.

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#124]
Our current benchmarks (see below) still take 10 minutes for large files (GBs) and 4-8 seconds for smaller files (MBs). This is a significant improvement from before, but deliveries involve thousands of products, so validate is still taking days instead of hours to run on one delivery. We need to figure out where else we can improve performance.

This new requirements is specific to improving all parts of validation separate from content validation.

Large test data sets are on `pds-dev-el7:/path/to/test/data/insight_cameras`

<img width="843" alt="Screen Shot 2019-10-04 at 9 37 00 AM" src="https://user-images.githubusercontent.com/33492486/66224621-3543f700-e68b-11e9-8737-5fe30770e3ef.png">

NOTE: You may need to execute with a catalog file or against multiple products to see improved performance. The initial loading of schemas/going out to internet will always take some time.

**Comment by hhlee445** [comment]
@jordanpadams Jordan, can you give exact path of the test data you indicated in the description?

**Comment by hhlee445** [comment]
Before adding a command chain, time command returns 
11.675u 0.557s 0:04.00 305.5%	0+0k 0+0io 0pf+0w

After adding 'pds4.label.skip.content' command chain, time command returns
11.373u 0.561s 0:03.79 314.7%	0+0k 0+0io 0pf+0w
