### ISSUE TITLE
Add validated product counter to pass/fail reporting and end summary

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#132]
Per conversations with GEO and RMS, a counter should be added to pass/fail report dialog to include a counter (validated/to go) in order to be able to monitor status. In addition, in the final output summary, the old VTool included a "validated" number at the end report to show successful validated products

**Comment by hhlee445** [comment]
Added a section in the end summary as: 

  Number of Passed product(s)/folder(s):  1
  Number of Failed product(s)/folder(s):  4
  Number of Skipped product(s)/folder(s): 0
  Total Number of product(s)/folder(s):   5

**Comment by jordanpadams** [comment]
Reopening for now until PR has been merged

**Comment by hhlee445** [comment]
Modified to have the count of product only.

  Number of Passed product(s):  1
  Number of Failed product(s):  4
  Number of Skipped product(s): 0
  Number of Total product(s):   5
