### ISSUE TITLE
Update config to include telescopes and facilities telescopes and facilities

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#135]
The two Context Products that validate can 't find below have been on  pds-gamma:/data/pds4/context-pds4/ for over a year. 

Hmmm, I couldn't directly attach the sample .xml and .tab files, so I appended .txt to both filenames.
[2035_stearns.xml.txt](https://github.com/NASA-PDS-Incubator/validate/files/3727629/2035_stearns.xml.txt)
[2035_stearns.tab.txt](https://github.com/NASA-PDS-Incubator/validate/files/3727630/2035_stearns.tab.txt)

% validate -t 2035_stearns.xml
Oct 14, 2019 11:29:04 PM com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector <clinit>
INFO: The optimized code generation is disabled
PDS Validate Tool Report
Configuration:
   Version                       1.17.0
   Date                          2019-10-15T06:29:00Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/2035_stearns.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/2035_stearns.xml
      ERROR  [error.label.context_ref_not_found]   line 50: 'Context product not found: urn:nasa:pds:context:facility:observatory.mauna_kea
      ERROR  [error.label.context_ref_not_found]   line 59: 'Context product not found: urn:nasa:pds:context:telescope:irtf.3m0
Validation complete.
Summary:
  2 error(s)
  0 warning(s)
  Message Types:
    2            error.label.context_ref_not_found
End of Report

**Comment by rchenatjpl** [comment]
Oh, wait, this is the same as https://osr.jpl.nasa.gov/jira/browse/PDS-835

**Comment by jordanpadams** [comment]
thanks @rchenatjpl. looks like this will be resolved from Harvest ingests these facilities / laboratories
