### ISSUE TITLE
Verify that all name/type attribute values correspond to names denoted context products

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#15]
Using similar methods to those for verify context products exist, validate should also check that if an Internal_Reference is given for an Observing_System_Component, Investigation_Area, or Target_Identification, we should ensure the <name> and <type> values match that in the Context_Product.

For example, a given observational product (or other) contain context product references in Observing System Component, Investigation_Area, and Target_Identification (and maybe 

Example of Observing_System_Component:
```
        <Observing_System>
            <name>MESSENGER MASCS</name>
            <Observing_System_Component>
                <name>MESSENGER</name>
                <type>Spacecraft</type>
                <Internal_Reference>
                    <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.mess</lid_reference>
                    <reference_type>is_instrument_host</reference_type>
                </Internal_Reference>
            </Observing_System_Component>
        </Observing_System>
```

#### Get the context product name
I think the easiest way to do this would be to add the name and type to the JSON file we already produce. So that would involve update the .py that generates the initial file, and the code that updates the file using the `-u` flag. If you look at a context product, you will see where that information is maintained (e.g. https://starbase.jpl.nasa.gov/pds4/context-pds4/instrument_host/spacecraft.orex_1.0.xml). I would just use the Xpaths `//name` and `//type` for now until we see if we get back bogus information. Note: some context products may not contain name/type so make sure we handle that error case.

#### Validate the name/type values in the label
Based upon the code, it looks like the validation of ContextProducts is happening in the `ContextProductReferenceValidationRule` class. Instead of tracking down specific classes to check where name/type are present, I think the best option is to:
1. Check if the context product reference is found (code already does this)
2. Go to the parent of the `Internal_Reference` and verify the name and type are valid based upon the JSON output.

e.g.
```
# From above example, code already checks this:
                <Internal_Reference>
                    <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.mess</lid_reference>
                    <reference_type>is_instrument_host</reference_type>
                </Internal_Reference>

# If that comes back as "valid", check the name/type values:
                <name>MESSENGER</name>   <---- THIS SHOULD MATCH VALUE IN CONTEXT PRODUCT
                <type>Spacecraft</type>   <---- THIS SHOULD MATCH VALUE IN CONTEXT PRODUCT
                <Internal_Reference>
                    <lid_reference>urn:nasa:pds:context:instrument_host:spacecraft.mess</lid_reference>
                    <reference_type>is_instrument_host</reference_type>
                </Internal_Reference>
```

#### Results
Throw a WARNING if the name/type does not match case-sensitive check.
Throw an ERROR if the name/type does not match in actual value (case-insensitive).

**Comment by danyu-pds** [comment]
@jordanpadams @galenhollins 
I am looking into this issue but not quite understand the requirement.
Could you email me details or have a short meeting with me when you have time?

**Comment by jordanpadams** [comment]
@danyu-pds see updated ticket information. let me know if you need more details
