### ISSUE TITLE
Update validate to throw error when a file has a space in the filename

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#153]
[iue_asteroid_spectra.zip](https://github.com/NASA-PDS-Incubator/validate/files/3844970/iue_asteroid_spectra.zip)
The attached bundle has a doc file with spaces in its file name, which is illegal per the Standards Reference:
6C.1.1 Rules
The following rules govern selection of file names.
[snip...]
• The file name must be constructed from the character set
A-Z ASCII 0x41 through 0x5A,
a-z ASCII 0x61 through 0x7A,
0-9 ASCII 0x30 through 0x39,
dash “-” ASCII 0x2D,
underscore “_” ASCII 0x5F, and
period “.” ASCII 0x2E.

However, validate allows it:
% validate -t iue_asteroid_spectra/
PDS Validate Tool Report
Configuration:
   Version                       1.17.5
   Date                          2019-11-14T06:38:41Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/iue_asteroid_spectra/]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/bundle_iue_asteroid_spectra.xml
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/collection_iue_asteroid_spectra_document.xml
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.xml
Validation complete.
Summary:
  0 error(s)
  0 warning(s)
End of Report

Though somehow validate -R pds4.bundle complains
% validate -R pds4.bundle -t iue_asteroid_spectra/
PDS Validate Tool Report
Configuration:
   Version                       1.17.5
   Date                          2019-11-14T06:45:46Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/iue_asteroid_spectra/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/bundle_iue_asteroid_spectra.xml
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/collection_iue_asteroid_spectra_document.xml
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.xml
PDS4 Bundle Level Validation Results
  FAIL: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.pdf
      ERROR  [error.file.name_has_invalid_characters]   File name uses invalid character
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
  FAIL: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.xml
      ERROR  [error.file.name_has_invalid_characters]   File name uses invalid character
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/document/collection_iue_asteroid_spectra_document.xml
  PASS: file:/Users/rchen/Desktop/iue_asteroid_spectra/bundle_iue_asteroid_spectra.xml
Validation complete.
Summary:
  2 error(s)
  1 warning(s)
  Message Types:
    2            error.file.name_has_invalid_characters
    1            warning.file.not_referenced_in_label
End of Report

**Comment by qchaupds** [comment]
Between the time this issue was reported and today 12/10?2020, the code has been fixed.

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 130 % validate -R pds4.bundle --skip-context-validation  -r report_github153.json -s json -t src/test/resources/github153/iue_asteroid_spectra

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 133 % egrep '"status"|"label"|"message"' report_github153.json
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/bundle_iue_asteroid_spectra.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/document/collection_iue_asteroid_spectra_document.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.xml",
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.pdf",
          "message": "File name uses invalid character"
          "message": "File is not referenced by any label"
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/document/3juno_lwr01896_ines%20fits%20headers.pdfa.xml",
          "message": "File name uses invalid character"
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/document/collection_iue_asteroid_spectra_document.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github153/iue_asteroid_spectra/bundle_iue_asteroid_spectra.xml",

**Comment by qchaupds** [comment]
Upon further inspection, a new class need to be built to check for valid names.  Stay tune.
