### ISSUE TITLE
As a user, I want to validate PDF files are PDF/A

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#164]
Per section 8A.2.2 of the PDS4 SR, PDF files must be PDF/A-1a or PDF/A-1b.

> Each document must be saved in one or more PDS-compliant formats using the Product_Document class. PDS-compliant formats for documents are “flat UTF-8” text, PDF/A1a (which is preferred), or PDF/A-1b. 

https://pdfbox.apache.org/1.8/cookbook/pdfavalidation.html

---
UPDATE
After some digging and tracking down some resources from https://pdfa.org, it looks like veraPDF may be a better solution and it actually wraps PDFBox for us. It also appears to have active development ongoing, which is great as PDF continues to evolve:
 
https://verapdf.org/software/
https://docs.verapdf.org/develop/
https://github.com/veraPDF/veraPDF-library

**Comment by qchaupds** [comment]
The following lines are needed in pom.xml to enforce all the JAXB jar files are the same versions and also added the new pdfbox library:

   
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-impl</artifactId>
        <version>2.3.0.1</version>
    </dependency>
    
    <dependency>
        <groupId>com.sun.xml.bind</groupId>
        <artifactId>jaxb-xjc</artifactId>
        <version>2.3.0.1</version>
    </dependency>

    <dependency>
      <groupId>org.verapdf</groupId>
      <artifactId>pdfbox-validation-model</artifactId>
      <version>1.16.1</version>
    </dependency>

The issue may be the external libraries are using different versions of JAXB which causes validate to fail when parsing XML file.  Having all the versions the same make life easier.
