### ISSUE TITLE
CCB-282: Revert validation checks on strict file naming requirements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#192]
**Link to SCR:** https://pds-jira.jpl.nasa.gov/browse/CCB-282

**SCR Details:** 
[CCB-282.pdf](https://github.com/NASA-PDS-Incubator/validate/files/4325866/CCB-282.pdf)

**Software Changes Requested:**
Per the SCR, the file naming highlighted in sections 2B.2.2 and 2B.2.2.1 are recommendations, not requirements. Validate should only throw info messages when these issues are found.

**Comment by rchenatjpl** [comment]
If in fact any character can follow "collection", then validate is incorrectly ignoring the collection in the attached bundle:

% validate -R pds4.bundle -t m2
PDS Validate Tool Report
Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2021-03-20T08:33:09Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/m2/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/m2/bundle.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/collection-data-bst-1.0.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/MAGBST051790239_V1.xml
        3 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/MAGBST051782340_V1.xml
        4 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Users/rchen/Desktop/m2/bundle.xml
        1 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/collection-data-bst-1.0.xml
        2 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/MAGBST051790239_V1.xml
      WARNING  [warning.integrity.unreferenced_member]   Identifier 'urn:nasa:pds:mess-mag-raw:data-bst:magbst051790239::1.0' is not a member of any collection within the given target
        3 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/m2/data/MAGBST051782340_V1.xml
      WARNING  [warning.integrity.unreferenced_member]   Identifier 'urn:nasa:pds:mess-mag-raw:data-bst:magbst051782340::1.0' is not a member of any collection within the given target
        4 integrity check(s) completed
Summary:
  0 error(s)
  2 warning(s)
  Product Validation Summary:
    4          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    4          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    2            warning.integrity.unreferenced_member
End of Report
Completed execution in 4749 ms
% 
% 
% mv m2/data/collection-data-bst-1.0.xml m2/data/collection_data-bst-1.0.xml
% validate -R pds4.bundle -t m2
[no errors or warnings]

FYI, I 90% disagree that Section 6 of the SR says that any character can follow "bundle". That section says "The following file names are reserved for specific purposes... bundle*.xml", whereas Section 2B.2.2.1 is much more specific about what the directory should look like. Anyway, providers and nodes can ignore what I say. I have no way to enforce my comments.
[m2.zip](https://github.com/NASA-PDS/validate/files/6175135/m2.zip)
