### ISSUE TITLE
Change behaviour for printing of "dots" to show progress

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#197]
**Is your feature request related to a problem? Please describe.**
The printing of dots per amount of file validated is useful to show that the tool is still running, but ends up polluting logs and making them much less readable.

**Describe the solution you'd like**
Making this display optional would be an easy option.

**Describe alternatives you've considered**
Alternatively, normalising the counter such that e.g. 50 dots are displayed for the entire file would be fine.

**Comment by jordanpadams** [comment]
@msbentley i upped our mod function by an order of magnitude. on a 4.8GB image, it output a dot every ~15 seconds of validation (~9 minutes == 38 dots).

**Comment by rchenatjpl** [comment]
Did the dots go away? I just validated a bundle with 1 big file and a few small ones, and no dots showed. I can attach the file (val29/) if desired.
   Version                       1.22.3
   Date                          2020-04-29T01:15:27Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/test/testPrep/val29/]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/bundle_em16_tgo_nmd.xml
        1 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_pp/collection_data_partially_processed.xml
        2 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_pp/nmd_par_sc_uvis_20200309T124104-20200309T143040-29-10231-1.xml
        3 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_raw/nmd_raw_sc_uvis_20200309T124117-20200309T143020-28-10231-1.xml
        4 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_raw/collection_data_raw.xml
        5 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_raw/nmd_raw_sc_uvis_20200309T124054-20200309T131745-27-10231-1.xml
        6 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/test/testPrep/val29/data_raw/nmd_raw_sc_uvis_20200309T124104-20200309T143040-29-10231-1.xml
        7 product validation(s) completed

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    7          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped


End of Report
Completed execution in 46565 ms

**Comment by jordanpadams** [comment]
@rchenatjpl they should not have gone away, but they should come up much less often (e.g. on multiple GB files)

**Comment by rchenatjpl** [comment]
ah, ok, thanks. On a 5GB image that took 255 seconds, I got 3 dots
