### ISSUE TITLE
Build and unit tests do not pass on Windows OS

### ISSUE THREAD

**Issue by tdddblog** [NASA-PDS/validate#204]
**Describe the bug**
Has to disable unit tests to build.

**To Reproduce**
Run "mvn package"
See error
`
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running gov.nasa.pds.validate.ValidationIntegrationTests
[ERROR] Tests run: 12, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 35.878 s <<< FAILURE! - in gov.nasa.pds.validate.ValidationIntegrationTests
[ERROR] testGithub71  Time elapsed: 1.742 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: error.table.field_value_data_type_mismatch error message not expected. ==> expected: <0> but was: <2278>
	at gov.nasa.pds.validate.ValidationIntegrationTests.testGithub71(ValidationIntegrationTests.java:411)

[ERROR] testGithub84  Time elapsed: 1.508 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: 
No error messages expected.
{"title":"PDS Validation Tool Report","configuration":{"version":"1.23.0-SNAPSHOT","date":"2020-03-30T20:31:57Z"},"parameters":{"targets":"[file:/C:/ws/github/validate/src/test/resources/github71/ELE_MOM.xml]","userSpecifiedSchemas":"[file:/C:/ws/github/validate/src/test/resources/github71/pds/v1/PDS4_PDS_1700.xsd, file:/C:/ws/github/validate/src/test/resources/github71/test/v1/PDS4_TEST_1700.xsd]","userSpecifiedSchematrons":"[file:/C:/ws/github/validate/src/test/resources/github71/pds/v1/PDS4_PDS_1700.sch]","severityLevel":"WARNING","recurseDirectories":"true","fileFiltersUsed":"[*.xml, *.XML]","dataContentValidation":"off","productLevelValidation":"on","maxErrors":"100000","registeredContextsFile":"C:\\ws\\github\\validate\\src\\main\\resources\\util\\registered_context_products.json"},"productLevelValidationResults":[{"status":"FAIL","label":"file:/C:/ws/github/validate/src/test/resources/github71/ELE_MOM.xml","messages":[{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"WARNING","type":"warning.label.schema","line":93,"column":48,"message":"schema_reference.4: Failed to read schema document 'https://pds.nasa.gov/pds4/test/v1/PDS4_TEST_1700.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."},{"severity":"ERROR","type":"error.label.schema","line":93,"column":48,"message":"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'test:spacecraft_clock_start_count'."},{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"WARNING","type":"warning.label.schema","line":94,"column":47,"message":"schema_reference.4: Failed to read schema document 'https://pds.nasa.gov/pds4/test/v1/PDS4_TEST_1700.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."},{"severity":"ERROR","type":"error.label.schema","line":94,"column":47,"message":"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'test:spacecraft_clock_stop_count'."},{"severity":"ERROR","type":"error.label.schematron","line":16,"column":36,"message":"The attribute pds:information_model_version must be equal to the value '1.12.0.0'."}],"fragments":[],"dataContents":[]}],"summary":{"totalErrors":6,"totalWarnings":2,"messageTypes":[{"messageType":"error.label.unresolvable_resource","total":3},{"messageType":"error.label.schema","total":2},{"messageType":"error.label.schematron","total":1},{"messageType":"warning.label.schema","total":2}]}} ==> expected: <0> but was: <6>
	at gov.nasa.pds.validate.ValidationIntegrationTests.testGithub84(ValidationIntegrationTests.java:595)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ValidationIntegrationTests.testGithub71:411 error.table.field_value_data_type_mismatch error message not expected. ==> expected: <0> but was: <2278>
[ERROR]   ValidationIntegrationTests.testGithub84:595 No error messages expected.
{"title":"PDS Validation Tool Report","configuration":{"version":"1.23.0-SNAPSHOT","date":"2020-03-30T20:31:57Z"},"parameters":{"targets":"[file:/C:/ws/github/validate/src/test/resources/github71/ELE_MOM.xml]","userSpecifiedSchemas":"[file:/C:/ws/github/validate/src/test/resources/github71/pds/v1/PDS4_PDS_1700.xsd, file:/C:/ws/github/validate/src/test/resources/github71/test/v1/PDS4_TEST_1700.xsd]","userSpecifiedSchematrons":"[file:/C:/ws/github/validate/src/test/resources/github71/pds/v1/PDS4_PDS_1700.sch]","severityLevel":"WARNING","recurseDirectories":"true","fileFiltersUsed":"[*.xml, *.XML]","dataContentValidation":"off","productLevelValidation":"on","maxErrors":"100000","registeredContextsFile":"C:\\ws\\github\\validate\\src\\main\\resources\\util\\registered_context_products.json"},"productLevelValidationResults":[{"status":"FAIL","label":"file:/C:/ws/github/validate/src/test/resources/github71/ELE_MOM.xml","messages":[{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"WARNING","type":"warning.label.schema","line":93,"column":48,"message":"schema_reference.4: Failed to read schema document 'https://pds.nasa.gov/pds4/test/v1/PDS4_TEST_1700.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."},{"severity":"ERROR","type":"error.label.schema","line":93,"column":48,"message":"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'test:spacecraft_clock_start_count'."},{"severity":"FATAL_ERROR","type":"error.label.unresolvable_resource","message":"Error at index 0 in: \"%5Cws%5Cgithub%5Cvalidate%5Csrc\""},{"severity":"WARNING","type":"warning.label.schema","line":94,"column":47,"message":"schema_reference.4: Failed to read schema document 'https://pds.nasa.gov/pds4/test/v1/PDS4_TEST_1700.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>."},{"severity":"ERROR","type":"error.label.schema","line":94,"column":47,"message":"cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'test:spacecraft_clock_stop_count'."},{"severity":"ERROR","type":"error.label.schematron","line":16,"column":36,"message":"The attribute pds:information_model_version must be equal to the value '1.12.0.0'."}],"fragments":[],"dataContents":[]}],"summary":{"totalErrors":6,"totalWarnings":2,"messageTypes":[{"messageType":"error.label.unresolvable_resource","total":3},{"messageType":"error.label.schema","total":2},{"messageType":"error.label.schematron","total":1},{"messageType":"warning.label.schema","total":2}]}} ==> expected: <0> but was: <6>
[INFO] 
[ERROR] Tests run: 12, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
`

**Expected behavior**
Unit tests should pass

** Version of Software Used**
- Master branch
- Windows 10

**Comment by jordanpadams** [comment]
this has been fixed for a bit now with @ZarehGorjianJPL building and using the app on windows
