### ISSUE TITLE
Validate incorrectly fails ASCII_Integer field that is space-padded (empty) in Table_Character

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#206]
See https://github.com/NASA-PDS-Incubator/validate/issues/9#issuecomment-607975642

For resolution, we should be sure to include a regression test for both DSV and character tables to make sure both are being checked for the foreseeable future.

**Comment by LevN0** [comment]
This may not be the right place to ask a question, so apologies. However, do I understand correctly that engineering node believes an empty ASCII_Integer field (e.g. all blank) is valid in Table_Character? I cannot find any text allowing that. 

Cited appears to be 4C.1, however that section "describes the format of delimited tables". Table_Character is not a delimited table.

**Comment by msbentley** [comment]
Agreed @LevN0 0- I'm also a bit confused about the comments in these threads - it would be great to get the final word @jordanpadams on where empty values are allowed in Table_Character and Table_Delimited, and the references to the SR for each case, since I feel I'm going in circles on this one ;-)

**Comment by jordanpadams** [comment]
@msbentley @LevN0 Table_Delimited is straightforward, per 4C.1. For Table_Character, we are now seeing, this is less obvious and I also don't see this called out anywhere in the SR. I think this may have been an assumption we made in some of our regression test data that we maybe should not have taken. Should this be something raised at the DDWG? Maybe someone else knows where we can find this?

**Comment by jordanpadams** [comment]
@rchenatjpl ⬆️  any thoughts on the above discussion?

**Comment by rchenatjpl** [comment]
For the life of me I can't resurrect my thinking or what prompted the original issue or find the originals. I think for Issue #9, when you wrote, "@rchenatjpl invalid for a delimited table (PDS DSV), valid for a character table", I was surprised. I think, for me, that this only affects test cases. Sorry I can't help more
