### ISSUE TITLE
As a user, I want validate to raise a WARNING when differing versions of IM are used within a bundle

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#210]
**Is your feature request related to a problem? Please describe.**
Per https://pds-jira.jpl.nasa.gov/projects/SW/issues/SW-28:

> The Validate software should return a warning if, when validating a bundle against a particular version of the IM, any label should contain a different version of the IM (whether older or newer version).

---

**Triage Response**
This should be an optional flag that a user can enable if they would prefer all dictionaries follow the same IM version. Many bundles no longer follow this paradigm, but a warning may be useful here as it throws our software through a loop when we have differing versions ingested all at once.

**Comment by jordanpadams** [comment]
May be something we can raise as part of #188

**Comment by qchaupds** [comment]
@jordanpadams Jordan, would you clarify if the versions referring to are the versions from the label only or from the schemas and the schematrons as well?   Would validate keep a track of all versions from all labels and at the end report that there are more than one versions?    What if the user really is OK with it (as they are now)?

**Comment by jordanpadams** [comment]
@qchaupds let's warn for just the version of the labels. i know we read in the "stack" of dictionaries that each of the LDDs use, but let's not include those in this warning check.

**Comment by qchaupds** [comment]
The following flag:

--prefer-all-labels-same-information-model-version

will be added to allow the user to see a warning in the report if not all versions of the (IM) are the same.

Without the flag, there will be no warning.  This flag should work for pds4.bundle and multiple targets with the -t parameter.

An example WARNING message:

      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github210/bundle_cassini-huygens-coradar.xml",
      "messages": [
        {
          "severity": "WARNING",
          "type": "info.validation.general",
          "message": "Multiple versions (2) of Information Model (IM) found in this run:  1.12.0.0 1.10.0.0"
        }
      ],
      "fragments": [],
      "dataContents": []
    }

These two labels have different IM versions.

% grep information_model_version src/test/resources/github210/*.xml | egrep "bundle_cassini|Missing_Area_tag.xml"
src/test/resources/github210/BILQH07S314_D065_T008S02_V02_without_Missing_Area_tag.xml:    <information_model_version>1.12.0.0</information_model_version>
src/test/resources/github210/bundle_cassini-huygens-coradar.xml:        <information_model_version>1.10.0.0</information_model_version>

**Comment by gxtchen** [comment]
@jordanpadams @qchaupds 
Is --prefer-all-labels-same-information-model-version the flag is should be testing? I couldn't find it in the document nor with the -h flag.

**Comment by jordanpadams** [comment]
@gxtchen sorry for hte confusion. that was the original design, but we made this a WARNING all the time. no flag is necessary. see PR at https://github.com/NASA-PDS/validate/pull/312 for a couple example runs
