### ISSUE TITLE
As a user, I want to validate all data types possible per the PDS4 Information Model

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#212]
The current version of validate does not handle ALL data types. There are several missing and/or validate does not gracefully handle them.

See sub-tasks:
#155 #190 #7 #211

**Comment by jordanpadams** [comment]
Build 11.0 Descope Rationale: Staff pulled off onto other flight projects. This will be no impact the build and this ticket will be added to Build 11.1

**Comment by al-niessner** [comment]
All items moved to #534 at some previous time. Removed them from this epic and closing.
