### ISSUE TITLE
validate outputs an extra '.'

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#214]
validate on the attached puts out an initial dot. It's odd. It could be intentional, though I don't know what it indicates. Note that the data file has extra text after the end of the Table_Delimited, so validate must be smart about throwing an error if &lt;records&gt;'s value is less than the actual number of records.

% validate -x PDS4_PDS_1E00.xsd -S PDS4_PDS_1E00.sch -t ccb138a.xml
.PDS Validate Tool Report

Configuration:
   Version                       1.22.1
   Date                          2020-04-07T17:12:00Z
[Archive.zip](https://github.com/NASA-PDS-Incubator/validate/files/4446103/Archive.zip)
![Screen Shot 2020-04-07 at 09 56 07](https://user-images.githubusercontent.com/56557532/78700142-d8373100-78b9-11ea-8c36-1b4aab67d951.jpg)

**Comment by jordanpadams** [comment]
@rchenatjpl the `.` is a status for content validation. for very large files, that becomes a lot of dots. will create a separate ticket per your other concern regarding number of records
