### ISSUE TITLE
validate v1.22.3 has large performance degradation on products with many tables

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#219]
**Describe the bug**
validate 1.22.3 has introduced a large performance drop on products with many tables - presumably related to the new checks on record numbers introduced (issue #149). We have a product with thousands of tables defined in one data object. The data product itself is only 350 MB but validation is still ongoing after 30 minutes. This worked fine under previous versions.

**Comment by hhlee445** [comment]
@msbentley Can I get a test data that you used?

**Comment by hhlee445** [comment]
@rchenatjpl Richard, do you have any test data with thousands of tables defined in one data object.

**Comment by rchenatjpl** [comment]
The max I've seen is ~10. Let me know if you want me to find such a file, but it will take some time.

**Comment by jordanpadams** [comment]
@hhlee445 can we try the few data files out at `pds-dev-el7:/data/home/pds4/testdata/urn-nasa-pds-kaguya_grs_spectra`? they are spectra so they are basically like all these tables?

**Comment by msbentley** [comment]
Hi @jordanpadams - sorry, again the data are not yet public :-( For background, the team in question archive a binary fits cube, but also wanted an ASCII-only version of the same data, so provide a version in which each slide of the cube is a table, hence the large number of them. I can fake some data, but will need some time (also for the table length issue, if still needed) - hopefully I can do this next week!

**Comment by jordanpadams** [comment]
@msbentley we (@hhlee445) should have a fix for the table length issue sometime over the next few days. once those changes are merged, we can let you know, and you can grab the development version and we can see if that helps with either of these issues. we hopefully have some test data that mimics your issues.
