### ISSUE TITLE
validate unexpectedly throws error for subdir named data/data/

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#221]
$ validate -R pds4.bundle -t attachedDir
...
PDS4 Bundle Level Validation Results
...
  FAIL: file:/Users/rchen/Desktop/bundle_psi/data/data/
      ERROR  [error.sub_directory.unallowed_name]   Directory name is not allowed except in the bundle root directory

I think having a subdir named data/data should be legal. If it's not, please cancel this issue.

[bundle_psi.zip](https://github.com/NASA-PDS-Incubator/validate/files/4536196/bundle_psi.zip)

**Comment by msbentley** [comment]
That's an interesting one... 6C.2.2 of the standards reference lists `data` as a reserved directory name, so I would think that validate is behaving itself here?

**Comment by rchenatjpl** [comment]
OK, that sounds good.
