### ISSUE TITLE
Deprecate -f and -m flags

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#23]
These flags are no longer applicable to Validate Tool. The label itself should be self-validating, and schema/schematron versions should be specified by the labels themselves, not by validate tool.

**Comment by msbentley** [comment]
Does this mean that when validating a collection/bundle labels with different IM versions, products will be validated correctly against the version in each label?

**Comment by jordanpadams** [comment]
Correct. That will now be the default functionality, versus right now, you have to remember to use the -f flag.

**Comment by hhlee445** [comment]
@ @galenatjpl Is there any sample label(s) to use for the validate tool?

**Comment by hhlee445** [comment]
Deprecated -f and -m flags and added a note to use '-x' and/or '-S' flags when it fails in default mode.

**Comment by jordanpadams** [comment]
@hhlee445 excellent! can we make sure we get a PR created for this? looks like the changes are still just in your branch.

**Comment by hhlee445** [comment]
Done. You should see a PR.
