### ISSUE TITLE
lid validation does not accept logical_identifier text to start with a newline

### ISSUE THREAD

**Issue by salvioli** [NASA-PDS/validate#235]
**Describe the bug**
`validate` considers invalid a lid of a label that starts with a newline (which could be for instance due to automatic wrapping at a certain line length).
The error raised is a schematron error so I imagine this issue may need to be moved to the information model repository. Let me know if that is the case.
This may affect other fields of the label too.
Both CRLF and LF newlines cause the issue.

**To Reproduce**
1. run validate against the attached product [rm_raw_rr_wheel_hdrm_temp_20191118t170058.583z_20191122t170058.583z.zip](https://github.com/NASA-PDS/validate/files/4722284/rm_raw_rr_wheel_hdrm_temp_20191118t170058.583z_20191122t170058.583z.zip)
```txt
 validate -t rm_raw_rr_wheel_hdrm_temp_20191118t170058.583z_20191122t170058.583z.xml
```
2. The product validation fails as reported in the attached [report.txt](https://github.com/NASA-PDS/validate/files/4722278/report.txt)

**Expected behavior**
The product lid should be considered valid even if the text XML node text includes trailing or leading newlines.

**Version of Software Used**
Output from `validate -V`
```text
gov.nasa.pds:validate
Version 1.23.1
Release Date: 2020-05-16 12:00:03

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
```

**Comment by jordanpadams** [comment]
@salvioli this validation is performed as part of the PDS4 Schematron and I believe is an intended strictness of validation. this is something that will need to be brought to the DDWG for discussion if a change is desired. 

https://pds.nasa.gov/datastandards/documents/im/current/index_1E00.html#attribute_pds_ascii_lid_pds_pattern

**Comment by salvioli** [comment]
Ok thanks for the clarification
