### ISSUE TITLE
As a user, I want to verify bundle directories adhere directory naming standards per SR

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#239]
L5.PRP.VA.10 The tool shall verify the following directory naming rules:
a)Directory names follow directory-naming rules. (6C.2.1 [7])
b)Directory names do not match prohibited directory names. (6C.2.3 [7])

**Comment by jordanpadams** [comment]
Implemented in Build 7b

**Comment by rchenatjpl** [comment]
Did this get implemented? I don't see an error for the attached, in which I renamed data/ to badname/.
% validate -R pds4.bundle -t 202010.carbonateReview

PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2020-12-05T10:28:37Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/202010.carbonateReview/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json



Product Level Validation Results

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/bundle_carbonate_refractive_indices.xml
        1 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/collection_data_inventory.xml
        2 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/dolomite.xml
        3 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/magnesite.xml
        4 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/calcite.xml
        5 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/document/collection_document_inventory.xml
        6 product validation(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/document/carbonate_refractive_indices_overview.xml
        7 product validation(s) completed


PDS4 Bundle Level Validation Results

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/collection_data_inventory.xml
        1 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/document/collection_document_inventory.xml
        2 integrity check(s) completed

  FAIL: file:/Users/rchen/Desktop/202010.carbonateReview/.DS_Store
      ERROR  [error.file.name_has_invalid_characters]   File name uses invalid character
      WARNING  [warning.file.not_referenced_in_label]   File is not referenced by any label
        3 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/bundle_carbonate_refractive_indices.xml
        4 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/calcite.xml
        5 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/dolomite.xml
        6 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/document/carbonate_refractive_indices_overview.xml
        7 integrity check(s) completed

  PASS: file:/Users/rchen/Desktop/202010.carbonateReview/badname/magnesite.xml
        8 integrity check(s) completed

Summary:

  1 error(s)
  1 warning(s)

  Product Validation Summary:
    7          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    7          check(s) passed
    1          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.file.name_has_invalid_characters
    1            warning.file.not_referenced_in_label

End of Report
Completed execution in 4941 ms
[202010.carbonateReview.zip](https://github.com/NASA-PDS/validate/files/5646865/202010.carbonateReview.zip)

**Comment by jordanpadams** [comment]
@rchenatjpl no. Sorry if we screwed that up. Per the log trail above, #240 is on our radar I believe for this next build. The requirement was just created so it can be tied into the RDD. Hopefully we can get all the requirements in the system next time to make this a little less confusing. Sorry about that!

**Comment by jordanpadams** [comment]
per @edguinness this refers to rules in Chapter 2 of the SR, which are a suggested directory scheme, not requirement
