### ISSUE TITLE
validate 1.24.0-SNAPSHOT chokes on a probably good file

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#243]
I think but am not sure the input is valid. An earlier validate passed the input:
% validate -V
gov.nasa.pds:validate
Version 1.24.0-SNAPSHOT
Release Date: 2020-05-12 16:01:40
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% validate -t x.xml
PDS Validate Tool Report
Configuration:
   Version                       1.24.0-SNAPSHOT
   Date                          2020-07-24T09:43:07Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/x.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/x.xml
    Begin Content Validation: file:/Users/rchen/Desktop/x.tnf
      ERROR  [error.table.records_mismatch]   table 2: Number of records read is not equal to the defined number of records in the label (expected 24877, got 0).
    End Content Validation: file:/Users/rchen/Desktop/x.tnf
        1 product validation(s) completed
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.table.records_mismatch
End of Report
Completed execution in 5256 ms
% 
% 
% 
% /PDS4.10a.tools/validate-1.17.5/bin/validate -V
gov.nasa.pds:validate
Version 1.17.5
Release Date: 2019-10-25 14:39:13
Core Schema: PDS4_PDS_1D00.xsd
Core Schematron: PDS4_PDS_1D00.sch
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% /PDS4.10a.tools/validate-1.17.5/bin/validate -t x.xml
...........................................................PDS Validate Tool Report
Configuration:
   Version                       1.17.5
   Date                          2020-07-24T09:43:53Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/x.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /PDS4.10a.tools/validate-1.17.5/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/x.xml
Validation complete.
Summary:
  0 error(s)
  0 warning(s)
End of Report
[Archive.zip](https://github.com/NASA-PDS/validate/files/4971248/Archive.zip)

**Comment by jordanpadams** [comment]
@rchenatjpl  this is hopefully related to #233 #234 .

@hhlee445 can you use this as an additional test file and hopefully this closes out nicely?
