### ISSUE TITLE
Add output directory flag to validate-bundle tool

### ISSUE THREAD

**Issue by riverma** [NASA-PDS/validate#246]
**Is your feature request related to a problem? Please describe.**
In support of the InSight mission, we at PDS Imaging Node use the parallelized `validate-bundle` tool to validate delivered bundles efficiently. We've automated the invocation of `validate-bundle` such that a remote process running on a system managed user home directory calls `validate-bundle` against a delivered bundle directory (and `bundle.xml` file). What this translates to is that the directory where `validate-bundle` is invoked is _different_ than the directory where we want the output of the `validate-bundle` reports to be generated. Currently, `validate-bundle` doesn't have a configuration argument to specify where the generated report directory is located. This means the generated report directory (e.g. `validate_20200918_150143`) is sent by default to the user's home directory - which makes diagnosing problems complicated for our operators. 

**Describe the solution you'd like**
- New command-line argument allowing the ability to specify where the `validate-bundle` generated directory that contains reporting output is located, similar to the current `validate` configuration parameter `-r,--report-file <file name>` - but instead for a report directory, i.e. something like `-r,--report-directory <directory>`

**Describe alternatives you've considered**
Running the `validate-bundle` tool in the directory where we wish to generate the report directory. We use remote connection automation that makes doing this cumbersome and more complex than using a command-line argument.

**Comment by jordanpadams** [comment]
@riverma

**Comment by riverma** [comment]
Thanks @jordanpadams and @qchaupds! Will test this out at the next mission data release opportunity.

**Comment by jordanpadams** [comment]
@riverma we have also closed out #238 and should have #254 closed out in the next few days (all thanks to @qchaupds )

**Comment by gxtchen** [comment]
@jordanpadams It would be good if it is in the document and in -h.

**Comment by gxtchen** [comment]
@jordanpadams never mind, I found it.
