### ISSUE TITLE
Improvements for validating accumulating bundles / collections

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#249]

**Comment by jordanpadams** [comment]
October Schedule Status ⏳:  On track

**Comment by jordanpadams** [comment]
📆  November Schedule Status: On track

**Comment by jordanpadams** [comment]
Closed per closure of all sub-tickets

**Comment by jpl-jengelke** [comment]
@jordanpadams: Was this associated with any particular sprint for tracking purposes?

**Comment by jordanpadams** [comment]
@jpl-jengelke not especially. this is a top-level Epic/theme for schedule-tracking purposes. if you install the [Zenhub extension for your browser](https://www.zenhub.com/extension) you should see all the child tickets associated with this.

additionally, issue is labeled with the build this was associated with, which in this case is B11.1, which was delivered ~1 year ago

**Comment by jpl-jengelke** [comment]
> @jpl-jengelke not especially. this is a top-level Epic/theme for schedule-tracking purposes. if you install the [Zenhub extension for your browser](https://www.zenhub.com/extension) you should see all the child tickets associated with this. ... additionally, issue is labeled with the build this was associated with, which in this case is B11.1, which was delivered ~1 year ago

Okay, thanks. I'm trying to sort out an unlabeled test suite in TR. This clears up my questions.
