### ISSUE TITLE
validate does not perform expediently when doing bundle-level validation against large bundles

### ISSUE THREAD

**Issue by riverma** [NASA-PDS/validate#254]
**Describe the bug**
When invoking `validate` against a large bundle (i.e. 100k+ of files), and explicitly skipping product-validation, validate still takes hours to days to complete (estimated 2 days at a rate of 2 files per second being evaluated). 

According to @jordanpadams - `validate` should run in the time frame of "minutes" typically when running without product validation, though it hasn't been tested against bundles containing hundreds of thousands of products.

**To Reproduce**
1. Download the latest InSight bundle: https://pds-imaging.jpl.nasa.gov/data/nsyt/insight_cameras/
2. Run `validate` with skipping of product-level validation: 
```
validate -R pds4.bundle --skip-product-validation -t insight_cameras/ --report-file validate-tool-run-report-noprodcheck.txt
```

3. Notice `validate` will be scanning every XML file at a rate of about 2 per second. This means a bundle of 100k+ files will take days to complete, which is largely the same as when running WITH product-level validation.

**Expected behavior**
After step 2 above, expect `validate` to return within a few minutes at most. 

Possible solutions:
- Include an option to check only non-product XML files
- Include parallelization support to speed up XML file processing

** Version of Software Used**
`1.24.0`

**Desktop (please complete the following information):**
 - OS: RHEL 7

**Comment by jordanpadams** [comment]
thanks @riverma we added this to our list
