### ISSUE TITLE
As a user, I want to run validate against object storage

### ISSUE THREAD

**Issue by riverma** [NASA-PDS/validate#266]
... so that I can execute validate on an S3 bucket

**Is your feature request related to a problem? Please describe.**
For future missions (e.g. M2020), there will be greater use of cloud services to process instrument data. This means that archival data releases to PDS _will_ be coming from data stored in the cloud. IMG would like to have the opportunity to run `validate` in the cloud itself, such that we can reduce the need to copy / transfer object store objects and minimize egress costs. 

In order to support the above scenario, we'd benefit from having `validate` be able to run against object stores, not just file systems, natively. Namely, object stores like [AWS S3](https://aws.amazon.com/s3/).  

**Describe the solution you'd like**
- The ability to have `validate` point to an object store bucket (e.g. s3 bucket) containing a PDS4 data release bundle and kick-off a validation run. In order to do this successfully, `validate` would have to take and understand PDS4 bundle descriptor files (e.g. `bundle.xml` etc.) and translate internal file references to object store locations (e.g. s3 objects)
- The ability for `validate` to benefit from and integrate with object store utilizing cloud processing services, e.g. [AWS Lambda](https://aws.amazon.com/lambda/) or [AWS EC2](https://aws.amazon.com/ec2/), where we can pass object store URIs to kick off processing runs. A scenario we're thinking is to have AWS pass refs to the latest S3 bucket objects as they arrive in S3, and run product validation as soon as the necessary prerequisite XML files are also available - i.e. lambda-based validation on-the-fly.

**Describe alternatives you've considered**
- `wget` or `aws cli` approaches documented in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonS3.html where we egress the products down from the cloud (expensive), or from a VM within the cloud (slow).
- s3 as an EFS: https://cloud.netapp.com/blog/amazon-s3-as-a-file-system (slow)

**Additional context**
This should part of a larger drive towards cloud-first technologies being developed by PDS

**Applicable requirements**
TBD

**Comment by jordanpadams** [comment]
@riverma we should have a more detailed conversation about the architecture here. several questions that come to mind:
1. do you plan on serving the data to users from AWS? or do you plan on downloading it to on-prem? (for the long term)
2. what is the timeline here? have you done any testing with any of these proposed solutions?
3. if you plan to serve the data to users, how do you plan on providing the abstraction layer to visualize the archive as a file structure?
4. per 3 above, this would help us understand how we may be able to leverage this abstraction layer to look like a bundle according the validate architecture.

**Comment by riverma** [comment]
Hi @jordanpadams - totally agreed. We need to have a more detailed discussion about this. Just wanted to create a ticket to begin the conversation and see how we can prepare `validate` for upcoming needs. Maybe we can agenda this in our next chat opportunity.

Some initial responses below:

> @riverma we should have a more detailed conversation about the architecture here. several questions that come to mind:
> 
> 1. do you plan on serving the data to users from AWS? or do you plan on downloading it to on-prem? (for the long term)

I believe the idea is to aim for the former long-term, the latter near-term if we don't have the right toolage available. This decision hasn't been hashed out yet though, so please take it in very general terms. 

> 2. what is the timeline here? have you done any testing with any of these proposed solutions?

I think M2020's timeline is a driver here. I don't have dates yet for their data releases, but we'll likely have to decide between serving their releases from the cloud or bringing it down back to prem soon. 

We have not begun testing the proposed solutions. We're currently in the tech evaluation / architecting phase of exploring a cloud-only solution.

> 3. if you plan to serve the data to users, how do you plan on providing the abstraction layer to visualize the archive as a file structure?

That's an excellent question. This is being addressed by our new Atlas revamp effort, where we're pursuing an entirely metadata-driven file exploration view. The underlying structure of the file system shouldn't limit us.

> 4. per 3 above, this would help us understand how we may be able to leverage this abstraction layer to look like a bundle according the validate architecture.

👍

**Comment by jordanpadams** [comment]
@riverma sounds good.

one last thing:

>> if you plan to serve the data to users, how do you plan on providing the abstraction layer to visualize the archive as a file structure?

> That's an excellent question. This is being addressed by our new Atlas revamp effort, where we're pursuing an entirely metadata-driven file exploration view. The underlying structure of the file system shouldn't limit us.

We can talk about this offline but I highly recommend looking into DataDrive (MGSS product) or an adaptation of DataDrive being worked by PO.DAAC for a similar use case.

**Comment by jordanpadams** [comment]
Triage Status: waiting on discussion with IMG before we can effectively triage and prioritize this effort

**Comment by jordanpadams** [comment]
per conversations with IMG, this will not be planned for build 11.0 or needed for M2020, so we will be moving this to backlog

**Comment by jordanpadams** [comment]
After some internal investigation, this can be done by using something like s3fs, but it is pretty inefficient for executing in a pipeline. We plan to move forward with using Docker, ECS, and EFS to execute validate.

For the remaining requests regarding finding products using S3, we will be using the Registry / Registry API for this as a separate step in the pipeline. A prerequisite for running validate will be to know the label and associated files. If a truly cloud-native validate is needed, a better requirement would be to be able to perform content validation using the Registry (e.g. given a lidvid, download and validate the label and associated products entirely using the Registry),
