### ISSUE TITLE
Registered context products file does not retain older versions of context products

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/validate#278]
The file **registered_context_products.json** that comes with Validate does not list all versions of context products. It lists only the latest versions. Therefore products that refer to the older versions are now invalid, according to Validate, which reports the error "error.label.context_ref_not_found". 

**To Reproduce**
1. Download a document from the InSight RISE document collection: https://pds-geosciences.wustl.edu/insight/urn-nasa-pds-insight_documents/document_rise/trk-2-34-revn-l5_tnf.xml 
2. Run Validate version 1.24.0 on this product, e.g. "validate trk-2-34-revn-l5_tnf.xml -R pds4.label -v1"
3. Observe resulting error message "ERROR  [error.label.context_ref_not_found]   line 34: 'Context product not found: urn:nasa:pds:context:investigation:mission.insight::1.0"
4. Observe that **urn:nasa:pds:context:investigation:mission.insight::1.0** is in fact a valid context product listed at https://pds.nasa.gov/data/pds4/context-pds4/investigation/mission.insight_1.0.xml. There is now a version 2.0 of this context product, but version 1.0 is still registered. 
5. Observe that **registered_context_products.json** lists only version 2.0 of this context product.

**Expected behavior**
I expected **registered_context_products.json** to include all versions of context products, so that archives that had previously passed validation would continue to pass.

** Version of Software Used**
Validate 1.24.0

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042 
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by jordanpadams** [comment]
**Proposed updates to validate logic:** check that LID matches and that version is >= version identified in the product

**Comment by jordanpadams** [comment]
@sslavney this should be fixed in the latest SNAPSHOT release of validate. feel free to test out, or you can wait until our next build in the spring once it has been sufficiently tested

**Comment by jordanpadams** [comment]
@sslavney btw, the latest unstable / SNAPSHOT release is here: https://github.com/NASA-PDS/validate/releases/tag/1.25.0-SNAPSHOT
