### ISSUE TITLE
Validate fails to report error in   File.file_size

### ISSUE THREAD

**Issue by radiosci** [NASA-PDS/validate#281]
[testdata.tar.gz](https://github.com/NASA-PDS/validate/files/5794084/testdata.tar.gz)
**Describe the bug**
Validate fails to report the error when class File, attribute file_size has an incorrect value

**To Reproduce**
Run validate on the attached *.{csv,xml} pair
It will pass.

**Expected behavior**
It should not pass

** Version of Software Used**
1.24.0

**Test Data / Additional context**
Included (see contents of  testdata.tar.gz)

**Screenshots**
Can provide if requested; should not be necessary.

**Desktop (please complete the following information):**
 - OS: Mac OS 11.1 (running validate from command line within Terminal window)
 - Browser: N/A
 - Version: N/A

**Applicable requirements**
 N/A

**Comment by jordanpadams** [comment]
@radiosci this bug should now be fixed. feel free to try out the latest development release and let us know if you run into any more issues: https://github.com/NASA-PDS/validate/releases/tag/1.25.0-SNAPSHOT
