### ISSUE TITLE
Implement initial framework to be able to start developing tests

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#282]
This ticket is intended to develop the initial framework for tests and how to create a new one. Each test should contain at least 1 success-oriented test case and at least 1 expected failure test case.

**Comment by qchaupds** [comment]
The test code for cucumber behavior testing will need to be compiled with:

% mvn package -DskipTests

The -DskipTests is to skip the (normal) existing integration tests.

A file will be created target/validate-1.25.0-SNAPSHOT-bin.zip by the command above and need to be unzipped with:

% cd target
% unzip validate-1.25.0-SNAPSHOT-bin.zip

A directory of .jar files will be created in validate-1.25.0-SNAPSHOT/lib

To run the cucumber testing assuming the version value in pom.xml for artifactId 'validate' is '1.25.0-SNAPSHOT'

% cd ../
% java -cp "target/test-classes:target/validate-1.25.0-SNAPSHOT/lib/*" io.cucumber.core.cli.Main target/test-classes/features

2 Scenarios (2 passed)
8 Steps (8 passed)
0m7.434s

There are currently two tests in the validate.feature feature file in src/test/resources/features directory.
The mvn command will create a copy of it to target/test-classes/features directory.

**Comment by tloubrieu-jpl** [comment]
This ticket needs a breakout discussion, as integration and cucumber tests need to be un sequentially.
