### ISSUE TITLE
Improve pds4.bundle validation performance

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#29]
Significant performance issues noted on large bundles. Specifically InSight team and Imaging Node experienced tool crashes due to Java Heap running out of space with settings >16GB. More details coming from Imaging Team.

Task includes:
* Benchmarking current performance noting any specific spikes on files or products
* Update software to eliminate performance issues
* Document new performance benchmarks and test plan / integration tests for ensuring benchmarks are met

**Comment by galenatjpl** [comment]
Some (or all memory issues) may have been addressed in this commit:
https://github.com/NASA-PDS-Incubator/validate/commit/cc119e14b5ac1a9e938a68809d7d3cf72be87bae

(put "29" in the commit message, but failed to put "#29", so it didn't get associated with this ticket).

<img width="691" alt="Screen Shot 2019-07-03 at 5 27 22 PM" src="https://user-images.githubusercontent.com/47542238/60632046-e058c200-9db7-11e9-8b6b-3ccfdc5aacd0.png">
<img width="688" alt="Screen Shot 2019-07-03 at 5 27 31 PM" src="https://user-images.githubusercontent.com/47542238/60632049-e77fd000-9db7-11e9-97cd-0c43f71cb208.png">
