### ISSUE TITLE
Migrate subset of existing regression tests to cucumber behavioral testing

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#290]
Let's migrate tests from this build to the new framework started in #282. here are a list of issues we can use for reference, but we do not need to create any new tests. Let's just migrate those that already have regression tests.

* #281 
* #278 
* #6 
* #256 
* #257 
* #246 
* #273 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Applicable requirements**
:unicorn: #1
:unicorn: #2

**Comment by tloubrieu-jpl** [comment]
@qchaupds  has issue with integration of cucumber test in maven.
