### ISSUE TITLE
Content validation incorrectly reports error for floating-point values out of specified min/max range

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/validate#294]
**Describe the bug**
With content validation turned on, Validate incorrectly issues the error message "error.table.field_value_out_of_min_max_range" for some floating-point fields in a CSV table, where Field_Statistics/maximum and Field_Statistics/minimum are defined. 

For example, given a field with this definition:

                <Field_Delimited>
                    <name>sample_time_increment</name>
                    <field_number>126</field_number>
                    <data_type>ASCII_Real</data_type>
                    <description>Time increment covered by each sample in this RDR-processed sounding</description>
                    <Field_Statistics>
                        <local_identifier>sample_time_increment_stats</local_identifier>
                        <maximum>0.12345</maximum>
                        <minimum>0.12345</minimum>
                    </Field_Statistics>
                </Field_Delimited>

Validate gives this error message:
      ERROR  [error.table.field_value_out_of_min_max_range]   table 1, record 357, field 126: Field has a value '0.12345' that is greater than the defined maximum value '0.12345'. 

There are two things going on here. 

First, apparently the internal representation of either the field maximum or the actual value has too much precision, e.g. 0.1234999999999 or something like that, which makes the comparison meaningless.

Second, Field_Statistics/minimum and Field_Statistics/maximum merely report the statistics for the value found in that data product, if I am reading the definitions correctly. They don't mean that values outside that range are invalid. So the message should be a warning, not an error. There's nothing wrong with the data; it's the label that needs to be fixed.

**To Reproduce**
Using the attached data file and label minmax-error.*, run Validate as follows:
validate minmax-error.xml -R pds4.label -v2 -r validate-minmax-error.txt --skip-context-validation
Notice the many error messages like the one in the example, apparently all for floating-point values (although I didn't do an exhaustive search).

**Expected behavior**
In cases like the example, where the actual value (0.12345) is within the expected min-max range, no error nor warning message should be issued.
In cases where the actual value is above Field_Statistics/maximum or below Field_Statistics/minimum, a warning message should be reported. It could be something like "Field has a value "nnn" that is greater than the expected maximum 'mmm'.
 
** Version of Software Used**
1.24.0

**Test Data / Additional context**
See attached label, data file, and validation report.

**Desktop (please complete the following information):**
 - OS: Windows 10

 - Browser: Chrome
 - Version: irrelevant
[validate-minmax-error.txt](https://github.com/NASA-PDS/validate/files/5954605/validate-minmax-error.txt)

[minmax-error.xml.txt](https://github.com/NASA-PDS/validate/files/5954608/minmax-error.xml.txt)
[minmax-error.csv.txt](https://github.com/NASA-PDS/validate/files/5954611/minmax-error.csv.txt)

**Comment by jordanpadams** [comment]
@sslavney we will work on this issue per the floating point issue. however, if the value is out of range of the min/max described in the label, I would consider this to be invalid since the label does not match the product? we try to only use warnings for things that can be optional, and sometimes are ignored. in this case, we would really want the data provider to go back and update this metadata.

does this make sense? if you disagree and believe this should only be a warning, we can maybe bring this up at the next Software Working Group meeting for discussion.

**Comment by sslavney** [comment]
@jordanpadams OK, error instead of warning.

**Comment by jordanpadams** [comment]
Closed per #296
