### ISSUE TITLE
Content validation of ASCII_Integer field does not accept value with leading zeroes

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/validate#297]
Given a Field_Delimited field with data_type ASCII_Integer, with Field_Statistics/minimum and Field_Statistics/maximum specified, Validate cannot read a value for that field with leading zeroes. For example, if Field_Statistics/maximum is 81, and the value in the data file is 00081, Validate gives the error message: 

ERROR  [error.table.field_value_not_a_number]   table 1, record 2, field 7: Cannot cast field value '00081' to a Number data type to validate against the min/max values defined in the label.

1. Using the attached example label and data file rimfax_rdr_0081_example.*, run Validate with the command:
  validate rimfax_rdr_0081_example.xml --skip-context-validation -r validate_rimfax_example.txt

2. The resulting output file validate_rimfax_example.txt will have the error message reported above.
Notice that the example CSV table has three records, one with the value in question as "81", one as "00081", and one as "   81". Only the value "00081" triggers the error message.

**Expected behavior**
I expected the value 00081 to be valid. 

** Version of Software Used**
1.24.0

**Test Data / Additional context**
[rimfax_rdr_0081_example.zip](https://github.com/NASA-PDS/validate/files/5996475/rimfax_rdr_0081_example.zip)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser n/a
 - Version n/a

**Comment by qchaupds** [comment]
It seems that the function that convert from a string to float number gets confused when leading zeros are presented.
A leading zero is interpreted as octal and the returned type is Integer but the code is expecting Double.
The digit '8' of "00081" is not a valid octal, thus the exception.  If the value was "00071", the exception may not have occur (haven't verify this yet).

"Integral values with a leading 0 will be interpreted as octal; the returned number will be Integer, Long or BigDecimal as appropriate."

An extra logic will need to be added to avoid this exception.

https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/math/NumberUtils.html

**Comment by qchaupds** [comment]
With the extra logic to remove the leading zeros for these types of numbers:

    FieldType.ASCII_REAL
    FieldType.ASCII_INTEGER
    FieldType.ASCII_NONNEGATIVE_INTEGER,

a run of validate against the provided labels resulted in success with no exception reported.

% validate --skip-context-validation -R pds4.label -r report_github297_label_valid.json   -s json -t src/test/resources/github297/valid/rimfax_rdr_0081_example.xml

% egrep "label|status" report_github297_label_valid.json | grep -v ruleType
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github297/valid/rimfax_rdr_0081_example.xml",

The code snippet in FieldValueValidator.java for reference:

`  private String correctLeadingZeroValue(String value) {
    // Some values may start with a zero but the user may not intend for it to be an Octal so
    // the leading zeros have to be removed:
    //       "00081"
    //        "-0081"

    // Check for negative sign and save it.
    boolean negativeSignFlag = false;
    if (value.startsWith("-")) {
        negativeSignFlag = true;
        value = value.substring(1);  // Move the pointer to "0081" if orignal value was "-0081"
    }

    if (value.startsWith("0")) {
        StringBuffer correctValue = new StringBuffer();
        boolean foundFirstNonZeroFlag = false;
        for (int i = 0; i < value.length(); i++) {
            // Inspect each character.  If haven't found a non-zero digit, keep skipping.
            if (foundFirstNonZeroFlag == false) {
                if (value.charAt(i) != '0') {
                    foundFirstNonZeroFlag = true;
                    correctValue.append(value.charAt(i));  // Add the first non zero character
                }
            } else {
                // If already found the firt non zero character, get all the characters to the end.
                correctValue.append(value.charAt(i));
            }

        }
        if (negativeSignFlag) {
            value = "-" + correctValue.toString();  // The corrected value of "-0081" is now "-81"
        } else{
            value =       correctValue.toString();  // The corrected value of "0081"  is now "81"
        }
     }
     return(value);
  }

  private void checkMinMax(String value, Double minimum, Double maximum,
      int fieldIndex, RecordLocation recordLocation, FieldType type) {

    if ((type == FieldType.ASCII_REAL || type == FieldType.ASCII_INTEGER || type == FieldType.ASCII_NONNEGATIVE_INTEGER) &&
        (value.startsWith("0") || value.startsWith("-0")))  {
        String originalValue = value;
        value = this.correctLeadingZeroValue(value);
        LOG.debug("checkMinMax:originalValue,value,minimum,maximum {},{},{},{}",originalValue,value,minimum,maximum);
    }

`
