### ISSUE TITLE
validate -u flag reports an error on Windows

### ISSUE THREAD

**Issue by edguinness** [NASA-PDS/validate#300]
Running validate with the '-u' flag to update the JSON file with a list of context LIDs throws an error. Sample output is shown below. Note it appears that the JSON file is updated even though an error message is displayed.

C:\Users\guinness>validate -u
java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\aaa\pds4\software\validate\bin\..\resources/registered_context_products.json
        at java.net.URI$Parser.fail(Unknown Source)
        at java.net.URI$Parser.checkChars(Unknown Source)
        at java.net.URI$Parser.parse(Unknown Source)
        at java.net.URI.<init>(Unknown Source)
        at gov.nasa.pds.validate.ValidateLauncher.getLatestJsonContext(ValidateLauncher.java:460)
        at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1375)
        at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1449)

PDS Validate Tool Report

Configuration:
   Version                       1.24.0
   Date                          2021-02-17T21:49:39Z

Parameters:
   Targets                       []
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      C:\aaa\pds4\software\validate\bin\..\resources\registered_context_products.json

Product Level Validation Results

Summary:

  0 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    0          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

End of Report
Completed execution in 3933 ms

**Comment by qchaupds** [comment]
An initial inspection may have pin point to the source of the error.  In Java, the file name separator is system dependent.  On linux/unix, the file separator is '/' whereas for Windows is the back slash.  Currently, the Java code hard-coded the '/' as a file separator which may have to be changed to fix the issue:

grep "ToolInfo.getOutputFileName" src/main/java/gov/nasa/pds/validate/ValidateLauncher.java 

        registeredProductsFile = new File(System.getProperty("resources.home") + "/" + ToolInfo.getOutputFileName());
                report.record(new URI(System.getProperty("resources.home") + "/" + ToolInfo.getOutputFileName()), p);
            report.record(new URI(System.getProperty("resources.home") + "/" + ToolInfo.getOutputFileName()), pList);
                    new File(System.getProperty("resources.home") + "/" + ToolInfo.getOutputFileName() + ".backup"));
                    new FileWriter(System.getProperty("resources.home") + "/" + ToolInfo.getOutputFileName()));

**Comment by jordanpadams** [comment]
resolved per #306
