### ISSUE TITLE
unclear error message for field count matching

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#301]
I've never encountered such a big file before, and I think it's only the size that causes the crash. I removed the first 2.8M data records, and validate worked, then I restored those and removed the last 2.8M data records, and validate worked. 

% ls -l u36*
-rw-rw-r--@ 1 rchen  703763885  1653600264 Feb 21 22:11 u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.tab
-rw-rw-r--@ 1 rchen  703763885       28573 Feb 21 22:22 u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
% grep records u36*xml
            <records>7800000</records>
% validate -V

gov.nasa.pds:validate
Version 1.25.0-SNAPSHOT
Release Date: 2020-12-11 01:55:32

Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.

% validate -t u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
..................................................java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at gov.nasa.pds.tools.validate.rule.AbstractValidationRule.execute(AbstractValidationRule.java:71)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at gov.nasa.pds.tools.validate.task.ValidationTask.execute(ValidationTask.java:134)
	at gov.nasa.pds.tools.validate.task.BlockingTaskManager.submit(BlockingTaskManager.java:27)
	at gov.nasa.pds.tools.label.LocationValidator.validate(LocationValidator.java:236)
	at gov.nasa.pds.validate.ValidateLauncher.doValidation(ValidateLauncher.java:1256)
	at gov.nasa.pds.validate.ValidateLauncher.processMain(ValidateLauncher.java:1494)
	at gov.nasa.pds.validate.ValidateLauncher.main(ValidateLauncher.java:1540)
Caused by: java.nio.BufferUnderflowException
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:303)
	at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:813)
	at gov.nasa.pds.objectAccess.ByteWiseFileAccessor.readRecordBytes(ByteWiseFileAccessor.java:237)
	at gov.nasa.pds.objectAccess.TableReader.getTableRecord(TableReader.java:233)
	at gov.nasa.pds.objectAccess.TableReader.getRecord(TableReader.java:214)
	at gov.nasa.pds.tools.validate.content.table.RawTableReader.getRecord(RawTableReader.java:173)
	at gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule.validateTableDataContents(TableDataContentValidationRule.java:467)
	... 12 more

PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2021-02-22T06:23:04Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json

Product Level Validation Results

  FAIL: file:/Users/rchen/Desktop/u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
      ERROR  [error.validation.internal_error]   Error executing validationTask: java.nio.BufferUnderflowException
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.internal_error

End of Report
Completed execution in 89448 ms

**Comment by rchenatjpl** [comment]
The file's too big to attach, so I'm putting it at pds-gamma:/home/rchen/val301.tgz
Please let me know when I can remove it.

**Comment by jordanpadams** [comment]
@rchenatjpl what version of validate are you using? we fixed this in October/November timeframe, so can you maybe try with the latest snapshot?  https://github.com/NASA-PDS/validate/releases/tag/1.25.0-SNAPSHOT

**Comment by rchenatjpl** [comment]
Ah, I should have checked. I had 
% validate -V
gov.nasa.pds:validate
Version 1.25.0-SNAPSHOT
Release Date: 2020-12-11 01:55:32

If I download the latest version, the error I had goes away, but now I'm getting a different odd message:

% validate -t ../Desktop/val301/u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
..............................................................................
PDS Validate Tool Report

Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2021-02-22T19:07:42Z

Parameters:
   Targets                       [file:/Users/rchen/Desktop/val301/u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json



Product Level Validation Results

  FAIL: file:/Users/rchen/Desktop/val301/u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
      ERROR  [error.validation.invalid_label]   The number of fields 15 do not match with fields provided: fieldFormatList.size() 0,fieldTypeList.size() 15,fieldNumberList.size() 15
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.validation.invalid_label

End of Report
Completed execution in 159544 ms

**Comment by jordanpadams** [comment]
@rchenatjpl copy. i will rename the bug and get it added to our list

**Comment by qchaupds** [comment]
Once Jordan approves the latest pull request, the code should work for you Richard @rchenatjpl and Jordan @jordanpadams 

https://github.com/NASA-PDS/validate/pull/296

https://github.com/NASA-PDS/validate/pull/296/commits/36f059f0632fc4e4c61f562f521727b7e28df712



A run shows the label passes.

validate -R pds4.label --skip-context-validation -r report_github301_label_valid.json   -s json -t /data/home/pds4/qchau/test_artifacts/github301/u36_irtf_320cm_2200nm_counts-v-time_rin
gs_ingress.xml >& t1 

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 171 % grep status report_github301_label_valid.json
      "status": "PASS",

The fixed code handles when the field 'field_format' is missing from the label since it is not a required tag in a label.

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/validate/commit/36f059f0632fc4e4c61f562f521727b7e28df712

**Comment by gxtchen** [comment]
The test file from Richard has been removed, can someone share the path if you still have the file?

**Comment by jordanpadams** [comment]
@rchenatjpl can you send over a test file to @gxtchen 

@gxtchen please use GitHub mentions on here (@username) wherever possible to try to contact someone. Otherwise the comments can get easily drowned out in GitHub email traffic

**Comment by rchenatjpl** [comment]
I tossed that file. Perhaps the SAs can restore it?

**Comment by jordanpadams** [comment]
@qchaupds do you have this test file?

@gxtchen if not, let's just skip this. As highlighted in the ticket. This was fixed per other tickets and other issues, so I think if we test the other tickets in this build, it can be assumed this was sufficiently tested

**Comment by qchaupds** [comment]
@gxtchen @jordanpadams Gary: If you need them, the files are here on pds-dev3 host:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 108 % ls -l /data/home/pds4/qchau/test_artifacts/github301/
total 1905452
drwxr-xr-x 2 qchau pds          6 Feb 22 13:06 invalid/
-rw-r--r-- 1 qchau pds 1653600264 Feb 21 22:11 u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.tab
-rw-r--r-- 1 qchau pds      28573 Feb 21 22:22 u36_irtf_320cm_2200nm_counts-v-time_rings_ingress.xml
-rw-r--r-- 1 qchau pds  297549113 Feb 22 13:06 val301.tgz
drwxr-xr-x 2 qchau pds          6 Feb 22 13:06 valid/
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 109 % 

As Jordan had pointed out, this issue is already fixed.  If you are paranoid, you can run the same test, just point the target to the same location as I did:

validate -R pds4.label --skip-context-validation -r report_github301_label_valid.json -s json -t /data/home/pds4/qchau/test_artifacts/github301/u36_irtf_320cm_2200nm_counts-v-time_rin
gs_ingress.xml >& t1

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 171 % grep status report_github301_label_valid.json
"status": "PASS",

**Comment by gxtchen** [comment]
@jordanpadams I agree, it is tested in 291, and 294.
