### ISSUE TITLE
As a user, I want to validate that the label references the PDS4 common schematron file which is required by standards

### ISSUE THREAD

**Issue by smclaughlin7** [NASA-PDS/validate#309]
Problem:
Although the PDS4 common schematron file is required to be referenced in a label, Validate only issues a WARNING if it is not specified.  

Background:
The NSSDCA's ingest process gleans information from bundle and primary collection products of a PDS4 submission in order to open new entries in the NSSDCA Master Catalog. But before it cracks open those products, it first checks the XML is valid based on the referenced PDS4 common schema/tron.  Our ingest process marked several LADEE LDEX collection products as invalid because the XML did not specify a schematron or schema file.

Solution:
Validate should issue an ERROR if a label does not reference the PDS4 common schem and schematron files. This solution should apply to all types of labels including, e.g., Product_SIP_Deep_Archive and Product_AIP.  

This issue is dependent on the approval of [https://pds-jira.jpl.nasa.gov/projects/CCB/issues/CCB-327](url)  "Require PDS4 labels to reference the PDS core schema and schematron and validate accordingly".

**Comment by jordanpadams** [comment]
@jshughes416  @edguinness is this something that is required in the IM or should the IM be updated to include this?

**Comment by jshughes** [comment]
This issue does not seem to affect the IM. Each PDS4 product label needs to include XML declaration statements for the associated XML Schema (.xsd) and Schematron (.sch) files. Since full validation requires the Schematron (.sch) file, the Validator should throw an error if a valid Schematron file reference is not provided.

**Comment by jordanpadams** [comment]
@jshughes copy that. so i guess per the schematron note, is there any requirement in the SR that the PDS common schematron is specified? that is the thing that I am checking on.

**Comment by smclaughlin7** [comment]
@jordanpadams @jshughes  Last month I withdrew the governing change request, https://pds-jira.jpl.nasa.gov/projects/CCB/issues/CCB-327, after the NSSDCA decided our front-end process will issue a WARNING instead of an ERROR if a bundle or collection label do not reference the PDS4 common schema and schematron files.  And due to several concerns and complexities about this issue, the DDWG had not arrived at an obvious solution after several discussions. However some members felt this topic should be kept on the back burner.

Do you recommend that I/we close this Validate ticket?  Thanks!

**Comment by jordanpadams** [comment]
@smclaughlin7 sounds good. we will close this as wontfix for now and can reopen as needed

**Comment by smclaughlin7** [comment]
Thanks @jordanpadams !
