### ISSUE TITLE
Validate missing collections in bundle after CCB-282 updates

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#310]
**Describe the bug**
See comment from @rchenatjpl at https://github.com/NASA-PDS/validate/issues/192#issuecomment-803272575

**Comment by qchaupds** [comment]
I am wondering if the name patterns are too strict.  @jordanpadams Can you clarify?  The SDR mentions bundle but quiet on collection page 14.

 vi ./src/main/java/gov/nasa/pds/tools/validate/BundleManager.java

public class BundleManager {
    private static final Logger LOG = LoggerFactory.getLogger(BundleManager.class);
    private static final Pattern COLLECTION_LABEL_PATTERN =
      Pattern.compile("(.*_)*collection(_.*)*\\.xml", Pattern.CASE_INSENSITIVE);
    private static final Pattern BUNDLE_LABEL_PATTERN =
      Pattern.compile("(.*_)*bundle(_.*)*\\.xml", Pattern.CASE_INSENSITIVE);

From what I can gather, the code looks for files that has "bundle_" or "collection_" which would explain why when Richard changed the name, it doesn't complain because it was found in the crawler.

**Comment by qchaupds** [comment]
On page 15, there is an example of a collection that has the name "collection_browse.xml"

**Comment by jordanpadams** [comment]
@qchaupds we want to look for any file that is `bundle*.xml` for bundles and and `collection*.xml` for collections.

**Comment by tloubrieu-jpl** [comment]
@qchaupds is looking at alternatives to crawl for the bundle and collection labels using apache library (fileUtil).

**Comment by qchaupds** [comment]
The first listFiles() function here:

https://commons.apache.org/proper/commons-io/javadocs/api-2.5/org/apache/commons/io/FileUtils.html

with IOFilter as a parameter is causing the code to pause (possibly in an infinite loop).  An alternate function listFiles() with extensions as an array of file extension ("xml") seems to work and get around the pause issue.  Will give that a try to see the regression tests will run successful and the work for issue #310 can proceed.

**Comment by jpl-jengelke** [comment]
@jordanpadams During testing the underscore error doesn't show up but the test data doesn't pass, either: 
[310_execution.txt](https://github.com/NASA-PDS/validate/files/7287485/310_execution.txt)
[test_310-1.txt](https://github.com/NASA-PDS/validate/files/7287487/test_310-1.txt)
[test_310-2.txt](https://github.com/NASA-PDS/validate/files/7287488/test_310-2.txt)

Is this OK?

**Comment by jordanpadams** [comment]
@jpl-jengelke we had a bug filed for this 1 day after you posted this comment :-) https://github.com/NASA-PDS/validate/issues/408 . Can you try this again with the latest tagged version of validate?
