### ISSUE TITLE
As a user, I want to validate all internal references from one product to another exist within the archive

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#316]
## Motivation
...so that I can ensure the referential integrity of product references throughout the entire PDS4 system

## Additional Details
Follow-on to #308 

## Acceptance Criteria
**Given** a product that contains 1 or more `Internal_Reference`s to a product
**When I perform** validation of the product
**Then I expect** the software to check that any references to products using the `lid_reference` and `lidvid_reference` attributes exist in the archive through the Registry

**Comment by miguelp1986** [comment]
@al-niessner can you please provide test cases for us to test?
