### ISSUE TITLE
B12.0 Content Validation Improvements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#318]

**Comment by jordanpadams** [comment]
📆 April status: On schedule

**Comment by jordanpadams** [comment]
All sub-tasks completed

**Comment by gxtchen** [comment]
@jordanpadams @tloubrieu-jpl Hi Jordan, is this a place holder for all validation improvements? Where can I get more information regarding the improvements?

Thanks.

**Comment by jordanpadams** [comment]
Hey Gary,

It is a "release theme" which has several child tickets.

Please install the zenhub extension for you browser and you should see all the child tasks associated with this "theme".

https://www.zenhub.com/extension



Jordan

--
Jordan Padams
Engineering Node Manager
Planetary Data System (PDS)
NASA Jet Propulsion Laboratory
***@***.***
626.390.9480




-------- Original message --------
From: Gary Chen ***@***.***>
Date: 9/17/21 12:32 PM (GMT-05:00)
To: NASA-PDS/validate ***@***.***>
Cc: "Padams, Jordan H (US 398A)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-PDS/validate] B12.0 Content Validation Improvements (#318)


@jordanpadams<https://urldefense.us/v3/__https://github.com/jordanpadams__;!!PvBDto6Hs4WbVuu7!auCtXvRkGyiF1dPhrLoOWSkK52dim732qTv6oMXCcar1GI8WP8NWqEaNHAu3I7InQjA-6NdDWw$> @tloubrieu-jpl<https://urldefense.us/v3/__https://github.com/tloubrieu-jpl__;!!PvBDto6Hs4WbVuu7!auCtXvRkGyiF1dPhrLoOWSkK52dim732qTv6oMXCcar1GI8WP8NWqEaNHAu3I7InQjC5exWGjQ$> Hi Jordan, is this a place holder for all validation improvements? Where can I get more information regarding the improvements?

Thanks.
