### ISSUE TITLE
validate bundle incorrectly reports "not a member of any collection" that it passed before

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#328]
Validate warns that the one Product_Document "is not a member of any collection within the given target" in the attached. I don't see it, and neither does an older version of validate.
[k2.zip](https://github.com/NASA-PDS/validate/files/6346607/k2.zip)

% validate -V
gov.nasa.pds:validate
Version 2.0.2
Release Date: 2021-04-07 17:52:09
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% 
% 
% validate -R pds4.bundle -t k2
PDS Validate Tool Report
Configuration:
   Version                       2.0.2
   Date                          2021-04-20T20:46:41Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/k2/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/k2/bundle_misc.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/Collection_document_cassini_v1.0.xml
        3 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Users/rchen/Desktop/k2/bundle_misc.xml
        1 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/Collection_document_cassini_v1.0.xml
        2 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml
      WARNING  [warning.integrity.unreferenced_member]   Identifier 'urn:nasa:pds:misc:document_cassini:pds3_titan_neutrals_ug_itar_sep2011::1.0' is not a member of any collection within the given target
        3 integrity check(s) completed
Summary:
  0 error(s)
  1 warning(s)
  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    3          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            warning.integrity.unreferenced_member
End of Report
Completed execution in 4073 ms
% 
% 
% ../PDS4.11.0.tools/validate-1.25.0-SNAPSHOT/bin/validate -V
gov.nasa.pds:validate
Version 1.25.0-SNAPSHOT
Release Date: 2021-03-23 00:13:27
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% 
% 
% ../PDS4.11.0.tools/validate-1.25.0-SNAPSHOT/bin/validate -R pds4.bundle -t k2
PDS Validate Tool Report
Configuration:
   Version                       1.25.0-SNAPSHOT
   Date                          2021-04-20T20:47:22Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/k2/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4.11.0.tools/validate-1.25.0-SNAPSHOT/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/k2/bundle_misc.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/Collection_document_cassini_v1.0.xml
        3 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/Collection_document_cassini_v1.0.xml
        1 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/k2/bundle_misc.xml
        2 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/k2/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml
        3 integrity check(s) completed
Summary:
  0 error(s)
  0 warning(s)
  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    3          check(s) passed
    0          check(s) failed
    0          check(s) skipped
End of Report
Completed execution in 4140 ms

**Comment by jordanpadams** [comment]
@qchaupds i wonder if this is an uppercase / lowercase issue?

**Comment by rchenatjpl** [comment]
holy cow, you're right, if "Collection...xml" is "collection...xml", it works. Ummm, I'm not sure what you want to do. The current behavior is reasonable, but I know of a few Collection*.xml

**Comment by qchaupds** [comment]
Currently, validate defines tokens to check for collections using lowercases.

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 155 % grep COLLECTION ./src/main/java/gov/nasa/pds/validate/constants/Constants.java
    public static final Pattern COLLECTION_LABEL_PATTERN = Pattern.compile("(.*)*collection(.*)*\\.xml",  Pattern.CASE_INSENSITIVE); // Ease the requirement to have an underscore after 'collection'.
    public static final Pattern SIMPLE_COLLECTION_LABEL_PATTERN = Pattern.compile("collection(.*)*\\.xml",Pattern.CASE_INSENSITIVE); // Ease the requirement to have an underscore after 'collection'.
    public static final String COLLECTION_NAME_TOKEN = "collection"; 
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 156 % 

I can't say definitely that it it all has to be lowercase but the examples I've seen are lowercases.

Section 2B.2.2.1 Root Directory:

https://pds.nasa.gov/datastandards/documents/sr/v1/StdRef_1.14.0.pdf

has examples using lowercases for bundle.

**A bundle is described by a label with the name “bundle[_*].xml”**

so it is reasonable to apply the same principle to collection filenames.

**Comment by qchaupds** [comment]
The last definition:

**public static final String COLLECTION_NAME_TOKEN = "collection";**

so I suspect that it is used to check if "collection" is in the file name.  Perhaps we can make sure that it lower the cases before checking for the "contains" function.

**Comment by rchenatjpl** [comment]
Sorry, I didn't state this bluntly. I think this is 100% a political decision. In my mind, all lower case is correct. However, EN (first Ron, then me) has created a few Collection*.xml, which I can of course change, but PPI has also created Collection* for three bundles. Joe Mafi has been pushing Jordan to weaken validate, and this is one of the weakenings.

**Comment by jordanpadams** [comment]
@qchaupds let's allow `Collection`. your proposed solution to lowercase the filename before the check seems reasonable.

**Comment by qchaupds** [comment]
So far so good.  We have successfully validated the bundle you'd provided without any WARN messages.  That means the file with "Collection" is now accepted:

% validate -R pds4.bundle  -r report_github328_bundle_valid.json   -s json -t src/test/resources/github328

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 101 % ls -lctr *.json | tail -1
-rw-r--r-- 1 qchau pds  2151 May 10 09:05 report_github328_bundle_valid.json
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 102 % egrep "status|label" report_github328_bundle_valid.json
    "allowUnlabeledFiles": "false",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/bundle_misc.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/document_cassini/Collection_document_cassini_v1.0.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/document_cassini/Collection_document_cassini_v1.0.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/bundle_misc.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github328/document_cassini/TITAN_NEUTRALS_UG_ITAR_SEP2011.xml",

**Comment by jpl-jengelke** [comment]
@jordanpadams This ticket did not pass testing with the following report(s): 
[328_execution.txt](https://github.com/NASA-PDS/validate/files/7287213/328_execution.txt)
[test_328-1.txt](https://github.com/NASA-PDS/validate/files/7287214/test_328-1.txt)

Guidance was "Should fail because the file name is misspell Kollection_document_cassini_v1.0.xml." This did not cause the test to fail.
