### ISSUE TITLE
verified that version 2.0.2 can break when running on java 8

### ISSUE THREAD

**Issue by bharris-igpp** [NASA-PDS/validate#332]
We ran version 2.0.2, accidentally, on Java 8.  It works for most bundles.  With the attached bundle, it would hang for hours, no error output of any kind.  This same bundle did not fail on Java 14.

[VG1-failed.zip](https://github.com/NASA-PDS/validate/files/6393743/VG1-failed.zip)

**Comment by jordanpadams** [comment]
@bharris-igpp can you try again with this latest SNAPSHOT version?

https://github.com/NASA-PDS/validate/releases/tag/v2.1.0-SNAPSHOT

**Comment by jordanpadams** [comment]
per email convo with @bharris-igpp this has been resolved
