### ISSUE TITLE
validate -u exits badly

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#333]
It might have worked. I was trying to get the hyb2 context products into validate, and that happened. But why the error message, and did it finish?

% validate -u
PDS Validate Tool Report
Configuration:
   Version                       2.1.0-SNAPSHOT
   Date                          2021-04-29T07:50:38Z
Parameters:
   Targets                       []
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
    Begin Fragment: https://pds.nasa.gov/services/search
      INFO  [info.validation.general]   Successfully updated registered context products config file. 
      INFO  [info.validation.general]   2600 registered context products found.
    End Fragment: https://pds.nasa.gov/services/search
        1 product validation(s) completed
java.lang.StringIndexOutOfBoundsException: begin 0, end -2, length 0
% 
% 
% date
Thu Apr 29 00:51:04 PDT 2021
% 
% 
% ls -l /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
-rw-r--r--@ 1 rchen  JPL\Domain Users  704803 Apr 29 00:50 /Users/rchen/PDS4tools/validate/resources/registered_context_products.json

**Comment by jordanpadams** [comment]
@rchenatjpl I think this may have been fixed with 2.0.3. can you verify?

**Comment by rchenatjpl** [comment]
Yes, it looks good
