### ISSUE TITLE
validate 2.1.0 snapshot fails on a label with 2 table_character

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#334]
The attached passes under validate 2.0.2 but fails under validate 2.1.0 snapshot. I think it should pass, though maybe I missed something in the Standards. My guess is that whatever is counting fields is not resetting after the first table_character.

 % validate --version
gov.nasa.pds:validate
Version 2.1.0-SNAPSHOT
Release Date: 2021-04-23 17:53:06
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% 
% 
% validate -t pvoro_graph_eden_k91_3a_01_v01_r00.xml
PDS Validate Tool Report
Configuration:
   Version                       2.1.0-SNAPSHOT
   Date                          2021-04-29T20:21:02Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/atmRev/pvoro_graph_eden_k91_3a_01_v01_r00.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/atmRev/pvoro_graph_eden_k91_3a_01_v01_r00.xml
      ERROR  [error.validation.invalid_label]   The number of fields 8 do not match with fields provided: fieldFormatList.size() 10,fieldTypeList.size() 10,fieldNumberList.size() 10
        1 product validation(s) completed
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.validation.invalid_label
End of Report
Completed execution in 3716 ms
% 
% 
% ../../PDS4.11.1.tools/validate-2.0.2/bin/validate --version
gov.nasa.pds:validate
Version 2.0.2
Release Date: 2021-04-07 17:52:09
Copyright 2019, by the California Institute of Technology ("Caltech").
All rights reserved.
% 
% 
% ../../PDS4.11.1.tools/validate-2.0.2/bin/validate -t pvoro_graph_eden_k91_3a_01_v01_r00.xml
PDS Validate Tool Report
Configuration:
   Version                       2.0.2
   Date                          2021-04-29T20:21:40Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/atmRev/pvoro_graph_eden_k91_3a_01_v01_r00.xml]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4.11.1.tools/validate-2.0.2/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/atmRev/pvoro_graph_eden_k91_3a_01_v01_r00.xml
        1 product validation(s) completed
Summary:
  0 error(s)
  0 warning(s)
  Product Validation Summary:
    1          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
End of Report
Completed execution in 3636 ms
% 
[Archive.zip](https://github.com/NASA-PDS/validate/files/6401455/Archive.zip)

**Comment by qchaupds** [comment]
Initial inspection shows the field_number values gets re-number to 1 and 2 after 8.

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github334 115 % grep field_number pvoro_graph_eden_k91_3a_01_v01_r00.xml
                    <field_number>1</field_number>
                    <field_number>2</field_number>
                    <field_number>3</field_number>
                    <field_number>4</field_number>
                    <field_number>5</field_number>
                    <field_number>6</field_number>
                    <field_number>7</field_number>
                    <field_number>8</field_number>
                    <field_number>1</field_number>
                    <field_number>2</field_number>

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github334 116 % grep fields pvoro_graph_eden_k91_3a_01_v01_r00.xml
                <fields>8</fields>
                <fields>2</fields>
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github334 117 % 

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github334 117 % grep Table pvoro_graph_eden_k91_3a_01_v01_r00.xml
        <Table_Character>
            <name>Pioneer Venus Orbiter Occultation Graphical Electron Density Header Table</name>
        </Table_Character>
        <Table_Character>
            <name>Pioneer Venus Orbiter Occultation Graphical Electron Density Body Table</name>
        </Table_Character>
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github334 118 % 

The error message seems to indicate that validate did not recognize there are more than one table in the label.

[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - testTableDefinition:tablePath,fieldPath,groupFieldPath //*:Table_Binary[namespace-uri()='http://pds.nasa.gov/pds4/pds/v1'],*:Record_Binary[namespace-uri()='http://pds.nasa.gov/pds4/pds/v1']/*:Field_Binary[namespace-uri()='http://pds.nasa.gov/pds4/pds/v1'],*:Record_Binary[namespace-uri()='http://pds.nasa.gov/pds4/pds/v1']/*:Group_Field_Binary[namespace-uri()='http://pds.nasa.gov/pds4/pds/v1']
[main] INFO gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - validateFieldFormats:target,recordCharacterNode file:/home/qchau/sandbox/validate/src/test/resources/github334/pvoro_graph_eden_k91_3a_01_v01_r00.xml,net.sf.saxon.tree.tiny.TinyElementImpl@404090
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - validateFieldFormats:fieldFormatList [, , , , , , , , , ]
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - validateFieldFormats:fieldTypeList [ASCII_String, ASCII_Real, ASCII_Date_Time_YMD, ASCII_Integer, ASCII_Real, ASCII_Real, ASCII_Real, ASCII_Real, ASCII_Real, ASCII_Real]
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - validateFieldFormats:fieldNumberList[1, 2, 3, 4, 5, 6, 7, 8, 1, 2]
[main] ERROR gov.nasa.pds.tools.validate.rule.pds4.TableFieldDefinitionRule - The number of fields 8 do not match with fields provided: fieldFormatList.size() 10,fieldTypeList.size() 10,fieldNumberList.size() 10

Will look in more details at next opportunity.

**Comment by qchaupds** [comment]
So far so good.  Validate now takes into account if multiple tables are used in the label when doing a check on the validity of the field types and format:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 98 % validate -R pds4.label  -r report_github334_label_valid.json   -s json -t src/test/resources/github334/pvoro_graph_eden_k91_3a_01_v01_r00.xml 

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 99 % egrep "status|label"  report_github334_label_valid.json
    "ruleType": "pds4.label",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github334/pvoro_graph_eden_k91_3a_01_v01_r00.xml",

Will do more testing to see that nothing else is broken.
