### ISSUE TITLE
Validate fails with Java Error

### ISSUE THREAD

**Issue by radiosci** [NASA-PDS/validate#337]
## 🐛 Describe the bug
Downloaded and installed Validate 2.0.3; encountered Java errors when tried to use.
Updated Java.
Still getting Java errors

## 📜 To Reproduce
1. Set up aliases so that "validate" executes "/usr/local/validate-2.0.3/bin/validate
2. Run "validate collection_dsn_redr.xml"
3. See error
4. Similar errors on all validations of *.xml labels

## 🕵️ Expected behavior
Validate 1.24.0 runs to completion with no errors before and after Java upgrade.
I was hoping for the same with Validate 2.0.3.

## 📚 Version of Software Used
Validate 2.0.3
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Mac OS 11.1 on MacBook Pro 2

## 🩺 Test Data / Additional context
[collection_dsn_redr.csv.gz](https://github.com/NASA-PDS/validate/files/6424935/collection_dsn_redr.csv.gz)
[collection_dsn_redr.xml.gz](https://github.com/NASA-PDS/validate/files/6424940/collection_dsn_redr.xml.gz)
[validate.rpt.gz](https://github.com/NASA-PDS/validate/files/6424941/validate.rpt.gz)

##  🏞Screenshots

validate.rpt (attached file) is complete output from failed run.

## 🖥 System Info
 - Mac OS 11.1 on MacBook. Pro 2
 - Safari 14.0.2

---

** :unicorn: Applicable requirements**

**Comment by jordanpadams** [comment]
@radiosci sorry about that. I will tag a new version built with java8 once we get these other couple bug fixes in

**Comment by jordanpadams** [comment]
@radiosci as a note, if you install openjdk11+ it should work. Some of of our tools (like the registry) are starting to require newer versions of Java. But will rebuild validate regardless.

**Comment by jordanpadams** [comment]
fixed per https://github.com/NASA-PDS/pds4-jparser/pull/41
