### ISSUE TITLE
Snapshot dependency on validate 2.0.2 / 2.0.3

### ISSUE THREAD

**Issue by fran-vallejo** [NASA-PDS/validate#339]
## 🐛 Describe the bug
validate 2.0.x references opencsv 5.4-SNAPSHOT which, as it is a snapshot version, is not available to download from maven central.

## 📜 To Reproduce
1. Clone validate repository - git clone https://github.com/NASA-PDS/validate.git
2. Checkout validate 2.0.2 tag - git checkout v2.0.2
3. Build validate - mvn clean package

Those steps should be executed without connection to PDS nexus to mimic an external user.

## 📚 Version of Software Used
Tried to build validate 2.0.2 and validate 2.0.3

##  🏞Screenshots
![buildError202](https://user-images.githubusercontent.com/52571100/117323823-859ac080-ae8f-11eb-8611-70a9c5ebf433.png)
![buildError203](https://user-images.githubusercontent.com/52571100/117323833-87fd1a80-ae8f-11eb-933f-01cb16429e6c.png)

## 🖥 System Info
 - OS: Ubuntu 18.04
 - Apache Maven 3.6.0
---

** :unicorn: Applicable requirements**

**Comment by msbentley** [comment]
Hi @jordanpadams do you have an idea how you might proceed here? This is blocking out integration of the latest versions of validate? Many thanks!

**Comment by jordanpadams** [comment]
@msbentley i can't replicate the issue noted above?

@fran-vallejo is this an issue you are still seeing? if i remember our previous conversation, this issue was because we have some dependencies that are SNAPSHOTs, but they should all be in the validate package itself. we do not have a PDS Nexus, so all of our dependencies have to be publicly accessible.

**Comment by fran-vallejo** [comment]
@jordanpadams at the end the problem was on our end so ... sorry for the trouble! 

Specifically, I declared our internal nexus as a mirror in my **˜/.m2/settings.xml** and that overrides the repo configuration declared in validate's pom.xml causing all the trouble. 
Removing the **\<mirrors>** section in **˜/.m2/settings.xml** fixes the problem.

Many thanks for your support.

**Comment by jordanpadams** [comment]
Thanks @fran-vallejo ! No problem. Those maven settings issues creep in all the time.
