### ISSUE TITLE
registered_context_products.json incorrect spacecraft name for MAVEN

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/validate#342]
## 🐛 Describe the bug
I do not know whether this is the place to report this bug or not, in any which case
I am sure this can be rerouted to where it should have been reported.

In the registered_context_products.json resource, the MAVEN s/c name is incorrect:

          {
               "name": [
                    "N/A"
               ],
               "type": [
                    "Spacecraft"
               ],
               "lidvid": "urn:nasa:pds:context:instrument_host:spacecraft.maven::1.0"
          },

## 🕵️ Expected behavior
Spacecraft name should be MAVEN

## 📚 Version of Software Used
Version 2.0.3

## 🖥 System Info

---

** :unicorn: Applicable requirements**

**Comment by jordanpadams** [comment]
@mcostasitja this information is taken directly from the context products that are released through engineering node. The context products must be invalid. Can you work with the lead node for MAVEN and @rchenatjpl to get this context product updated?

**Comment by mcostasitja** [comment]
@jordanpadams I will comment on the issue as I get a reply from the atmospheres node. Feel free to close the ticket if you consider it convenient.

**Comment by jordanpadams** [comment]
For reference, closing per comment above regarding a lack of information in context product metadata.

Here is the context product. It looks to not specify an Instrument_Host.name.

https://pds.nasa.gov/data/pds4/context-pds4/instrument_host/spacecraft.maven_1.0.xml
