### ISSUE TITLE
As a user I want to see the name of a table/array in errors, if one is specified

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#343]
## Motivation

Errors like this:
```
[ERROR] e.b.p.v.Pds4ValidatorImpl: srn_cal_sc_strofio_hk-status_20200429_20200429.cdf - array:55 location:70 Value is not within the valid range of the data type 'IEEE754LSBDouble': NaN
```
can be difficult to track down in objects with many tables/arrays. Rather than counting them in the label, it would be great if the array or table name (if specified, given that it's optional) could be displayed, e.g.
```
[ERROR] e.b.p.v.Pds4ValidatorImpl: srn_cal_sc_strofio_hk-status_20200429_20200429.cdf - array:55 (HV_NEG_1_5KV_LEVEL) location:70 Value is not within the valid range of the data type 'IEEE754LSBDouble': NaN
```

## Acceptance Criteria
**Given** That a table or array has a `name` attribute
**When I perform** a validation check which fails on this table/array
**Then I expect** the name of the table/array to be displayed in the output

**Comment by qchaupds** [comment]
@msbentley Help me to understand what the table or array name may look like?  
Better yet,  if you have an example label and data that you can share that may help me to see which code is affected when validate is ran against it.

**Comment by qchaupds** [comment]
What I am hinting at is how does the label specify the table or array name?  Is it the "local_identifier" tag?

An example:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github343/test_data 109 % view science_index_good.xml

     80     <Table_Character>
     81       <local_identifier>TABLE</local_identifier>
     82       <offset unit="byte">0</offset>
     83       <records>3</records>
     84       <description>Science Index Table</description>
     85       <record_delimiter>Carriage-Return Line-Feed</record_delimiter>
     86       <Record_Character>
     87         <fields>14</fields>

**Comment by msbentley** [comment]
Hi @qchaupds - I meant it quite literally, the `name` attribute ;-) e.g.

https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1G00.html#N-223121635

Thanks, Mark

**Comment by qchaupds** [comment]
@msbentley I am still foggy.  Given this example, tell me which field identify the name of the table or array:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 109 % view src/test/resources/github343/test_data/science_index_good.xml

     80     <Table_Character>
     81       <local_identifier>TABLE</local_identifier>
     82       <offset unit="byte">0</offset>
     83       <records>3</records>
     84       <description>Science Index Table</description>
     85       <record_delimiter>Carriage-Return Line-Feed</record_delimiter>
     86       <Record_Character>
     87         <fields>14</fields>
     88         <groups>0</groups>
     89         <record_length unit="byte">133</record_length>
     90         <Field_Character>
     91           <name>FILE_NAME</name>
     92           <field_number>1</field_number>
     93           <field_location unit="byte">1</field_location>
     94           <data_type>ASCII_String</data_type>
     95           <field_length unit="byte">26</field_length>
     96           <field_format>%-26s</field_format>
     97           <description>Name of the file.</description>
     98         </Field_Character>
     99         <Field_Character>
    100           <name>NUMBER</name>
    101           <field_number>2</field_number>
    102           <field_location unit="byte">28</field_location>
    103           <data_type>ASCII_String</data_type>
    104           <field_length unit="byte">8</field_length>
    105           <field_format>%-8s</field_format>
    106           <description>Number of the asteroid.</description>
    107         </Field_Character>
    108         <Field_Character>
    109           <name>NAME</name>
    110           <field_number>3</field_number>
    111           <field_location unit="byte">37</field_location>

I don't have a good example yet so the one I am using is from another test and trying to understand your issue.

**Comment by msbentley** [comment]
As in the description above, the `name` attribute is optional, so it can only be displayed if present. My proposal is to keep the current behaviour (numbering the table or array) but _also_ display the `name` if present.

**Comment by jordanpadams** [comment]
closed per #370

**Comment by jordanpadams** [comment]
@msbentley just as a heads up, we rolled back this change in the latest version if the IM. trying to carry along the name was a bit painful in the existing code, and even though it is a pain to use count, there is an existing workaround. if you would still like this implemented, we can re-add back to the backlog and revisit in the future.

**Comment by msbentley** [comment]
Hi @jordanpadams from a usability perspective, I still think this is important (simply to show the name, if present, when reporting an error). I have a few cases where the labels are complex and store dozens of tables or arrays, and then having to step through the label to find the error is quite painful and error-prone.

**Comment by jordanpadams** [comment]
@msbentley copy. we will see about adding this back in down the road

**Comment by al-niessner** [comment]
@jordanpadams @msbentley 

With an array name of image_90, changed the message from
```
      ERROR  [error.array.value_out_of_min_max_range]   array 1, location (99, 222):  Value is less than the minimum value in the label (min=-127.0, actual=-128)
```

to 

```
      ERROR  [error.array.value_out_of_min_max_range]   array image_90 or index 1, location (99, 222):  Value is less than the minimum value in the label (min=-127.0, actual=-128).
```

To make it more complete I think the base error should be `array index 1` when no name is given. Desires? Right now I have left it at `array 1`.

**Comment by jordanpadams** [comment]
closed per https://github.com/NASA-PDS/validate/pull/640
