### ISSUE TITLE
validate inexplicably writes to validate_stack_traces.log

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#344]
validate passes the attached bundle but writes something to validate_stack_traces.log, which is worrisome. I assume the bundle has no bugs, but it would be nice to be sure. I guess this issue has a good chance of being a wontfix, but really, don't you want to clean up these exceptions?

% validate -t uranus_occ_u36_maunakea_380cm
PDS Validate Tool Report
Configuration:
   Version                       2.0.4
   Date                          2021-05-15T10:19:52Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/uranus_occ_u36_maunakea_380cm/]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/uranus_occ_u36_maunakea_380cm/bundle.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/uranus_occ_u36_maunakea_380cm/data/collection_data.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/uranus_occ_u36_maunakea_380cm/data/u36_maunakea_380cm_2200nm_ring_beta_ingress_sqw.xml
        3 product validation(s) completed
Summary:
  0 error(s)
  0 warning(s)
  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
End of Report
Completed execution in 5319 ms

[uranus_occ_u36_maunakea_380cm.zip](https://github.com/NASA-PDS/validate/files/6485640/uranus_occ_u36_maunakea_380cm.zip)
[validate_stack_traces.log](https://github.com/NASA-PDS/validate/files/6485651/validate_stack_traces.log)

**Comment by qchaupds** [comment]
The issue was this line:

TableReader tmpReader = new TableReader(tableObjects.get(0), dataFile, false, false);

For some labels, there are no tableObjects so putting in a check of the size before accessing it resulted in no stack file printing.

**Comment by msbentley** [comment]
HI @jordanpadams et al. Just to confirm, under what conditions should we expect a stack trace log? With 2.0.7 we are still seeing this in cases where we would not expect it...

**Comment by jordanpadams** [comment]
@msbentley you should only see it when there is a fatal error if it is still appearing at other times, we will do a full scrub of the software to remove times when it is created unexpectedly

**Comment by msbentley** [comment]
OK, thanks @jordanpadams - let me know if you need some examples!

**Comment by qchaupds** [comment]
@msbentley @jordanpadams Yes, having an example would be nice to see where the code is writing to a stack trace log when it shouldn't.
I am combing through the code right now but haven't been able to pin-point what or where the trace log shouldn't be writing.

**Comment by msbentley** [comment]
This may be related to #379 but one other case I see is when the data file cannot be found (e.g. it is missing, or the filename in the label is wrong), e.g.

```
ERROR  [error.table.bad_file_read]   table 1: Error occurred while trying to read table: /home/mbentley/Dropbox/work/bepi/archive/test_products/minimal_test_product.csv (No such file or directory)
```
This generates `validate_stack_traces.log` and `validate_stack_traces.log.temp`

**Comment by qchaupds** [comment]
@msbentley Do you have an example of test data that when you run and validate is successful but still writes to stack trace log file.  It would help me to know where in the code that is happening.   As of right now, I cannot find it.
