### ISSUE TITLE
Improve validate reporting when trying to read a null row

### ISSUE THREAD

**Issue by tbarnes4** [NASA-PDS/validate#355]
## 🐛 Describe the bug
There are two related bugs.  First, the validate tool appears to be trying to read an extra CSV record when none exist, but it assumes one exists (could this be related to #89 where it is trying to read a file that doesn't exist).  Second, I think the tool is not correctly counting the number of records (counting from 0 instead of 1?).

In the example file, the first 22 records (or 2934 bytes) are header records.  Then there are 2241 tab delimited records.   PDS4 Viewer correctly reads all records.  Please note that this was migrated a long time ago and we should have probably defined a header object, but did not.

In validate 2.0.2 and 2.0.6 I get the following errors:
>   FAIL: file:/Volumes/echeclus04/TEMP/NSSDC_PDS4_prep/compil-comet_v2/halebopp/data/whypointsremovedfromdata.xml
    Begin Content Validation: file:/Volumes/echeclus04/TEMP/NSSDC_PDS4_prep/compil-comet_v2/halebopp/data/whypointsremovedfromdata.csv
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 1: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 2: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 3: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 4: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 5: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 6: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 7: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 8: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 9: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 10: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 11: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 12: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 13: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 14: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 15: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 16: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 17: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 18: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 19: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 20: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 21: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 22: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 23: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 24: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 25: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 26: Error while getting field value: null
      ERROR  [error.table.bad_field_read]   table 1, record 2241, field 27: Error while getting field value: null
    End Content Validation: file:/Volumes/echeclus04/TEMP/NSSDC_PDS4_prep/compil-comet_v2/halebopp/data/whypointsremovedfromdata.csv

In validate 1.24.0 I get the following error:

> ERROR  [error.table.records_mismatch]   table 1: Number of records read is not equal to the defined number of records in the label (expected 2241, got 2240).

## 📜 To Reproduce
1. Download example files:  
- https://pdssbn.astro.umd.edu/holdings/pds4-compil-comet:halebopp-v1.0/data/whypointsremovedfromdata.xml
- https://pdssbn.astro.umd.edu/holdings/pds4-compil-comet:halebopp-v1.0/data/whypointsremovedfromdata.csv
2. run the command: 

> % validate -R pds4.label whypointsremovedfromdata.xml

3. See error

## 🕵️ Expected behavior
Expect the tool to recognize when there are no more records and report that instead of trying to read a null record.  Also expect the tool to properly count the number of records.

## 📚 Version of Software Used
validate 1.24.0
validate 2.0.2
validate 2.0.6

## 🖥 System Info

---

## :unicorn: Applicable requirements**
* 🦄 https://github.com/NASA-PDS/validate/issues/149

## Engineering Details
- [ ] add check to content validation where if the record is null, fail gracefully indicating the record is null, versus checking every individual field anyway

**Comment by tbarnes4** [comment]
I found the error in the csv file.  There was a carriage-return line-feed enclosed in double quotes for one fields in one of the records (line 2062/3 of the file).  Therefore the number of records in the xml file is wrong should be minus one.  Still validate should report a better error and not try to read a record that does not exist.  Very clever to see validate take end of line characters in side a field.  Looks like other scripts do not.

**Comment by jordanpadams** [comment]
thanks @tdbarnes we will look to improve the errors returned

**Comment by tbarnes4** [comment]
@ jordanpadams Should the validate tool show that the carriage-return line-feed characters being included in a field as an error itself (illegal characters), instead of reading them in?  Per my understanding in 4C.1 of the Standard Reference:

> \<CR\> and \<LF\> may be used only in combination as a record delimiter. They may not be used, either separately or in combination, as part of a field value.

I mention this because this particular error would not have been discovered if there was not the other records count being off error.

Thanks!

**Comment by jordanpadams** [comment]
@tbarnes4 yes. validate should throw an error there. apparently we are allow CRLF anywhere in a table, but we should only allow in table_character.

**Comment by jordanpadams** [comment]
will create a separate ticket for that

**Comment by tbarnes4** [comment]
@ jordanpadams  Thanks!

**Comment by qchaupds** [comment]
Stripping the large files into one just 4 records (including the record that spanned two lines):

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 179 % tail -5 src/test/resources/github357/whypointsremovedfromdata_4_records.csv
,1995O1,,1995,7,30.09,a,S,10.3,,AC,38,L,5,65,,2.1,,2,,,ICQ 96,,BOR,,"REMOVED, failed stationary test pre-perihelion",
,1995O1,,1997,5,4.81,s,O,0.5,,SP,0,E,,1,,20,,7,7,55,ICQ103,,ZNO,"Did not use a magnitude method reported by Green (i.e. column 27 not being S, B, M, I, or E), prioritizing S then M",,
,1995O1,,1997,5,10.81,a,O,0.8,,SP,0,E,,1,,20,,7/,>3,,ICQ103,,"ZNO
","Did not use a magnitude method reported by Green (i.e. column 27 not being S, B, M, I, or E), prioritizing S then M",,
,1995O1,,1999,9,23.19,,S,12.4,:,HS,28,T,10,175,,1,,4,,,ICQ XX,,BIV,Poor Weather Reported,,

The current logic (is probably not correct) is reporting as it read each line:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 180 %  grep "validateTableContentLineWise" t2 | grep lineNumber
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableContentLineWise:POSITION_1:lineNumber,line 0,[,1995O1,,1995,7,30.09,a,S,10.3,,AC,38,L,5,65,,2.1,,2,,,ICQ 96,,BOR,,"REMOVED, failed stationary test pre-perihelion",
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableContentLineWise:POSITION_2:lineNumber,line 1,[,1995O1,,1997,5,4.81,s,O,0.5,,SP,0,E,,1,,20,,7,7,55,ICQ103,,ZNO,"Did not use a magnitude method reported by Green (i.e. column 27 not being S, B, M, I, or E), prioritizing S then M",,
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableContentLineWise:POSITION_2:lineNumber,line 2,[,1995O1,,1997,5,10.81,a,O,0.8,,SP,0,E,,1,,20,,7/,>3,,ICQ103,,"ZNO
[main] DEBUG gov.nasa.pds.tools.validate.rule.pds4.TableDataContentValidationRule - validateTableContentLineWise:POSITION_2:lineNumber,line 3,[","Did not use a magnitude method reported by Green (i.e. column 27 not being S, B, M, I, or E), prioritizing S then M",,

Still work in progress to count the number of fields from each record.  For record 3 (because it stopped prematurely), it should report that the number of fields read is less than the 27 promised (from the label).

It is also not counting the correct number of records read.

Hope to know more next week.

**Comment by qchaupds** [comment]
So far so good.   Able to detect the extra CR or LF inside the field value and report it:

      "dataContents": [
        {
          "dataFile": "file:/home/qchau/sandbox/validate/src/test/resources/github357/whypointsremovedfromdata.csv",
          "messages": [
            {
              "severity": "ERROR",
              "type": "error.validation.invalid_field_value",
              "table": 1,
              "record": 2040,
              "field": 24,
              "message": "Field value cannot contain a carriage return or linefeed for Table_Delimited"
            },

**Comment by qchaupds** [comment]
Since the issue in this ticket is related to #357, both will be worked on together on the same branch.

**Comment by qchaupds** [comment]
The code is now reporting if the number of records read is different than the "records" field in the label:

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github357 130 % grep records  whypointsremovedfromdata_2250_records.xml 
      <file_name>whypointsremovedfromdata_records_count_corrected.csv</file_name>
      <records>2250</records>

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate/src/test/resources/github357 131 % egrep "records|file_name" whypointsremovedfromdata_2250_records.xml 
      <file_name>whypointsremovedfromdata_records_count_corrected.csv</file_name>
      <records>2250</records>

The file whypointsremovedfromdata_records_count_corrected.csv has the bad record correctd so the actual number of recrods is 2240

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 156 % validate -R pds4.label -r report_github357_label_invalid_2250_records.json -s json -t src/test/resources/github357/whypointsremovedfromdata_2250_records.xml

Validate now count the correct number of records which is 2240 and it is smaller than the advertised 2250 records so it report the error below.

  "productLevelValidationResults": [
    {
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github357/whypointsremovedfromdata_2250_records.xml",
      "messages": [],
      "fragments": [],
      "dataContents": [
        {
          "dataFile": "file:/home/qchau/sandbox/validate/src/test/resources/github357/whypointsremovedfromdata_records_count_corrected.csv",
          "messages": [
            {
              "severity": "ERROR",
              "type": "error.table.records_mismatch",
              "table": 1,
              "message": "Number of records read is not equal to the defined number of records in the label (expected 2250, got 2240)."
            }
          ]
        }
      ]
    }
  ],

**Comment by jordanpadams** [comment]
@tbarnes4 this should be included in our latest release: https://github.com/NASA-PDS/validate/releases/tag/v2.0.7
