### ISSUE TITLE
Validate allows CRLF within a Table_Delimited field

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#357]
## 🐛 Describe the bug

Per 4C.1 of the Standards Reference regarding the PDS DSV:

> \<CR\> and \<LF\> may be used only in combination as a record delimiter. They may not be used, either separately or in combination, as part of a field value.

We should not allow CRLF within a Table_Delimited field.

## 📜 To Reproduce
Issue was found per https://github.com/NASA-PDS/validate/issues/355 .

## 🕵️ Expected behavior

Validate should check if there is a CR or LF within a Table_Delimited field, and raise an error if it exists.

## 📚 Version of Software Used

2.0.6

## 🩺 Test Data / Additional context

See https://github.com/NASA-PDS/validate/issues/355

---

**Comment by jpl-jengelke** [comment]
@jordanpadams I did not pass testing on this issue. That is because even when CTRL-V <enter> is inserted manually or when '\r' or '\n' are entered manually into CSV test data the test never fails. So it appears the CRLFs are not detected.

Moreover, the data appears insufficient to test this particular issue as a fail mode file would make it clear.

Please review. ...
[357_execution.txt](https://github.com/NASA-PDS/validate/files/7288267/357_execution.txt)
[test_357-1.txt](https://github.com/NASA-PDS/validate/files/7288268/test_357-1.txt)

**Comment by jordanpadams** [comment]
@jpl-jengelke this may be a bug. can you open an I&T Bug Report here? https://github.com/NASA-PDS/validate/issues/new/choose

**Comment by rchenatjpl** [comment]
Looks like the newer version fixed this. In the attached .csv, record 2 has an extra LF, and record 7 has an extra CR. validate reports (reasonably, not perfectly since the LF looks like a new record):
    Begin Content Validation: file:/Users/rchen/Desktop/test/val357.csv
      ERROR  [error.table.missing_CRLF]   table 1, record 2: Record does not end in carriage-return line feed.
      ERROR  [error.validation.invalid_field_value]   table 1, record 2, field 24: Field value cannot contain a carriage return or linefeed for Table_Delimited
      ERROR  [error.validation.invalid_field_value]   table 1, record 6, field 25: Field value cannot contain a carriage return or linefeed for Table_Delimited
      ERROR  [error.table.missing_CRLF]   table 1, record 7: Record does not end in carriage-return line feed.
    End Content Validation: file:/Users/rchen/Desktop/test/val357.csv
        1 product validation(s) completed
[Archive.zip](https://github.com/NASA-PDS/validate/files/7415739/Archive.zip)

**Comment by jordanpadams** [comment]
@rchenatjpl thanks. i agree the error reporting could potentially be improved, but it that require a much more complicated algorithm to move forward through a file, but then when you encounter an issue, go back to see if that is what you meant. if you think that would be helpful, we can add it, but I'm not sure how often this use cases actually happens?
