### ISSUE TITLE
validate does not parse colon in Windows path

### ISSUE THREAD

**Issue by sslavney** [NASA-PDS/validate#360]
## 🐛 Describe the bug
Validate 2.0.6 reports the colon in a typical Windows file path as an illegal character. For example, if the path is Z:\mydirectory\myfile.xml, the error message will be 

ERROR  [error.validation.internal_error]   Error executing validationTask: java.nio.file.InvalidPathException: Illegal char <:> at index 2: /Z:/mydirectory/myfile.xml

This happens **even when no path is specified** in the Validate command; that is, when the label to be validated is in the current working directory.

This didn't happen in the previous version of Validate, 1.24.0.

## 📜 To Reproduce
1. Use the attached label SuperCam_Bundle_SIS.xml, or any PDS4 label known to be valid.
2. With that label in the current working directory on a Windows system, run Validate 2.0.6 with the command "validate SuperCam_Bundle_SIS.xml -R pds4.label". (To capture the screen output, append " >validate-report.txt 2>&1 " to the command.)
3. Observe the above-mentioned error message in the output.

## 🕵️ Expected behavior
I expected Validate to report that the label passed without errors, which is what happens with Validate 1.24.0.

## 📚 Version of Software Used
Validate 2.0.6

## 🩺 Test Data / Additional context
A test label and the resulting report from Validate are attached.
[validate-2.0.6-error-report.zip](https://github.com/NASA-PDS/validate/files/6657471/validate-2.0.6-error-report.zip)

##  🏞Screenshots
n/a

## 🖥 System Info
 - OS: Windows 10
 - Browser: n/a

---

**Comment by LucasMiller** [comment]
@jordanpadams Hi Jordan, any luck resolving this issue? I ran into the same problem while using the tool to validate some recently produced products. Thanks!

**Comment by jordanpadams** [comment]
@LucasMiller this is in our queue to be worked on next. sorry for the delay

**Comment by jordanpadams** [comment]
@sslavney @LucasMiller this should be fixed in our latest release: https://github.com/NASA-PDS/validate/releases/tag/v2.0.7
