### ISSUE TITLE
validate does not allow ".XML" as an extension for a label file

### ISSUE THREAD

**Issue by seanhardman** [NASA-PDS/validate#364]
## 🐛 Describe the bug
Validate Tool generates an error when the extension of a PDS4 label file is capitalized ".XML". After reviewing the Standards Reference and the Data Provider's Handbook, it appears that there are no restrictions on the capitalization of PDS4 label extensions. In fact, capitalized extensions are allowed on other validation target files.

## 📜 To Reproduce
Steps to reproduce the behavior (notice the inconsistency in the "File Filters Used" parameter:

(base) MT-202412:bin shardman$ ./validate --skip-context-validation --skip-content-validation --target ../../test/MIS000XXX_2021001T000000_DEV0_2021001T0000_RAW010.XML

PDS Validate Tool Report

Configuration:
   Version                       2.1.0-SNAPSHOT
   Date                          2021-06-23T15:28:30Z

Parameters:
   Targets                       [file:/Users/shardman/dev/eurc/test/MIS000XXX_2021001T000000_DEV0_2021001T0000_RAW010.XML]
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             **[\*.xml, \*.XML]**
   Data Content Validation       off
   Product Level Validation      on
   Max Errors                    100000
   Registered Contexts File      /Users/shardman/dev/eurc/validate-2.1.0-SNAPSHOT/resources/registered_context_products.json

Product Level Validation Results

  FAIL: file:/Users/shardman/dev/eurc/test/MIS000XXX_2021001T000000_DEV0_2021001T0000_RAW010.XML
      ERROR  [error.label.bad_extension]   Label file names must end with the extension '.xml'
        1 product validation(s) completed

Summary:

  1 error(s)
  0 warning(s)

  Product Validation Summary:
    0          product(s) passed
    1          product(s) failed
    0          product(s) skipped

  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped

  Message Types:
    1            error.label.bad_extension

End of Report
Completed execution in 4817 ms

## 🕵️ Expected behavior
I expect the label to validate successfully.

## 📚 Version of Software Used
This behavior has been seen in versions 2.0.6 as well as 2.1.0-SNAPSHOT.

## 🩺 Test Data / Additional context
[MIS000XXX_2021001T000000_DEV0_2021001T0000_RAW010.XML.zip](https://github.com/NASA-PDS/validate/files/6703160/MIS000XXX_2021001T000000_DEV0_2021001T0000_RAW010.XML.zip)

##  🏞Screenshots
N/A

## 🖥 System Info
 - OS: Mac 10.15.7
 - Browser N/A
 - Version N/A

---

**Comment by jordanpadams** [comment]
@seanhardman this should be fixed in our latest release: https://github.com/NASA-PDS/validate/releases/tag/v2.0.7

**Comment by seanhardman** [comment]
Looks good. Thanks.

**Comment by jpl-jengelke** [comment]
@jordanpadams Executing the test fails with validate 2.1.0 SNAPSHOT, but it does not fail for the stated reason of ALL CAPS: 
[364_execution.txt](https://github.com/NASA-PDS/validate/files/7287464/364_execution.txt)
[test_364-1.txt](https://github.com/NASA-PDS/validate/files/7287465/test_364-1.txt)

Is this OK?

**Comment by jordanpadams** [comment]
@jpl-jengelke that is fine. we should really update that test data to actually be valid though. can you create a ticket for that? https://github.com/NASA-PDS/validate/issues
