### ISSUE TITLE
JAVA Path does not handle whitespaces in MAC as it used to

### ISSUE THREAD

**Issue by marcsit** [NASA-PDS/validate#37]
**Describe the bug**
The path for JAVA (in the user bash profile) does not handle whitespaces appropriately. Please note that this was not the case for 1.15dev or for 1.14:

**To Reproduce**
This was my JAVA_HOME is set to:

  export JAVA_HOME="/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home”

which exists and so on and on and works for 15-dev, somehow 15 does not seem to be able to cope with the whitespace I have tried:

  export JAVA_HOME="/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home”

and does not work, and I have tried to copy Java in:

  export JAVA_HOME="/Library/Internet/JavaAppletPlugin.plugin/Contents/Home”

and then it works. 

This behavior was not present in 1.15dev and 1.14.
Other users with no blankspaces did not experience this issue. 

**Expected behavior**

** Version of Software Used**
1.15.0

**Desktop (please complete the following information):**
 - OS: iOS Mojave 10.14.5 (18F132)
MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by jordanpadams** [comment]
@marcsit apologies for the inconvenience. we added some new functionality to dynamically attempt to get the JAVA_HOME without user intervention, but looks like we introduced a bug. We will definitely get this into the next minor version, if we don't deploy a hot fix before then.

**Comment by marcsit** [comment]
Thanks Jordan, no rush at all! (By the way I am Marc Costa, from ESAC. You might remeber me from the IPDA and PDW meetings)

**Comment by msbentley** [comment]
Putting quotes around the variable name in the shell script seems to fix it, at least to first order

**Comment by jordanpadams** [comment]
Just merged this fix
