### ISSUE TITLE
validate halts if label has name "collection" embedded

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/validate#375]
This may already be in an issue somewhere. Section 6C.1.3 of the PDS4 Standards says that collection*.[xml,csv] is reserved, but validate is choking on a file named something_collection.xml. Maybe some other part of the Standards or the DPH disallows "collection" as any part of the filename?  Anyway, the attached directory h/ has Product_Observational label data/primassl_visible_spectral_data_collection.xml
```
% validate -R pds4.bundle -t h
PDS Validate Tool Report
Configuration:
   Version                       2.0.6
   Date                          2021-07-19T06:55:55Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/h/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  FAIL: file:/Users/rchen/Desktop/h/
      FATAL_ERROR  [error.validation.internal_error]   Index 0 out of bounds for length 0
Summary:
  1 error(s)
  0 warning(s)
  Product Validation Summary:
    0          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    0          check(s) passed
    0          check(s) failed
    0          check(s) skipped
  Message Types:
    1            error.validation.internal_error
End of Report
Completed execution in 1459 ms
% 
% 
% mv h/data/primassl_visible_spectral_data_collection.xml h/data/primassl_visible_spectral_data_xxx.xml
% 
% 
% validate -R pds4.bundle -t h                                                                
PDS Validate Tool Report
Configuration:
   Version                       2.0.6
   Date                          2021-07-19T07:07:12Z
Parameters:
   Targets                       [file:/Users/rchen/Desktop/h/]
   Rule Type                     pds4.bundle
   Severity Level                WARNING
   Recurse Directories           true
   File Filters Used             [*.xml, *.XML]
   Data Content Validation       on
   Product Level Validation      on
   Allow Unlabeled Files         false
   Max Errors                    100000
   Registered Contexts File      /Users/rchen/PDS4tools/validate/resources/registered_context_products.json
Product Level Validation Results
  PASS: file:/Users/rchen/Desktop/h/bundle_gbo.ast.primass-l.spectra.xml
        1 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/h/data/collection_gbo.ast.primass-l.spectra_data.xml
        2 product validation(s) completed
  PASS: file:/Users/rchen/Desktop/h/data/primassl_visible_spectral_data_xxx.xml
        3 product validation(s) completed
PDS4 Bundle Level Validation Results
  PASS: file:/Users/rchen/Desktop/h/data/collection_gbo.ast.primass-l.spectra_data.xml
        1 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/h/bundle_gbo.ast.primass-l.spectra.xml
        2 integrity check(s) completed
  PASS: file:/Users/rchen/Desktop/h/data/primassl_visible_spectral_data_xxx.xml
        3 integrity check(s) completed
Summary:
  0 error(s)
  0 warning(s)
  Product Validation Summary:
    3          product(s) passed
    0          product(s) failed
    0          product(s) skipped
  Referential Integrity Check Summary:
    3          check(s) passed
    0          check(s) failed
    0          check(s) skipped
End of Report
Completed execution in 4409 ms
```
[h.zip](https://github.com/NASA-PDS/validate/files/6838675/h.zip)

**Comment by qchaupds** [comment]
The bug is in src/main/java/gov/nasa/pds/tools/validate/BundleManager.java.

After the function call at:

            ArrayList<String> collectionIdList = TargetExaminer.getTargetContent(target.getUrl(),PRODUCT_COLLECTION_ID_AREA_TAG,LOGICAL_IDENTIFIER_TAG,VERSION_ID_TAG);

The assumption was that the array collectionIdList would have at least two elements but sometimes it doesn't.  The exception is thrown when the 2nd index is accessed.

The fix is to check for the size of at least two:

           // Because the size returned of collectionIdList is not guaranteed to have at least 2 elements, make the check to
            // avoid the java.lang.IndexOutOfBoundsException violation.
            if (collectionIdList.size() < 2) {
                LOG.warn("selectMatchingReferenceFromCollection:Expecting at least 2 elements from collectionIdList: target.getUrl() {}",target.getUrl());
            } else {
                LOG.debug("selectMatchingReferenceFromCollection:target.getUrl() comparing reference {} {} {}",target.getUrl(),collectionIdList.get(0), collectionReferenceToMatch);
                LOG.debug("selectMatchingReferenceFromCollection:target.getUrl() comparing version   {} {} {}",target.getUrl(),collectionIdList.get(1), collectionVersionToMatch);
                LOG.debug("selectMatchingReferenceFromCollection:collectionIdList.get(0).split('::')[0],collectionReferenceToMatch [{}] [{}]",collectionIdList.get(0).split("::")[0],collectionReferenceToMatch);
                LOG.debug("selectMatchingReferenceFromCollection:collectionIdList.get(1),collectionVersionToMatch {} {}",collectionIdList.get(1),collectionVersionToMatch);
                if (collectionIdList.get(0).split("::")[0].equals(collectionReferenceToMatch) && collectionIdList.get(1).equals(collectionVersionToMatch)) {
                    childrenSelected.add(target);
                    LOG.debug("selectMatchingReferenceFromCollection:ADD_TARGET {}",target);
                }
            }


A sample run is successful:

 validate -R pds4.bundle --skip-context-reference-check -r report_github375_bundle.json -s json -t src/test/resources/github375/h/bundle_gbo.ast.primass-l.spectra.xml > & t1

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 141 % egrep "label|status"  report_github375_bundle.json
    "allowUnlabeledFiles": "false",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/bundle_gbo.ast.primass-l.spectra.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/data/collection_gbo.ast.primass-l.spectra_data.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/data/primassl_visible_spectral_data_collection.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/data/collection_gbo.ast.primass-l.spectra_data.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/bundle_gbo.ast.primass-l.spectra.xml",
      "status": "PASS",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github375/h/data/primassl_visible_spectral_data_collection.xml",

Will check the code in at next opportunity.
