### ISSUE TITLE
Checksums output lowercase and do not accept uppercase checksums

### ISSUE THREAD

**Issue by ARDWhite** [NASA-PDS/validate#376]
## 🐛 Describe the bug
Validate generates checksums with all lowercase letters. Bundle MD5 has checksums with uppercase letters. Validate flags checksum mismatch error despite matching sequences of letters/numbers.

## 📜 To Reproduce
- Input command "validate [bundle XML] -M [bundle MD5] -r [report.txt] -R pds4.bundle"
- Open [report.txt] file to read errors

## 🕵️ Expected behavior
Validate generates checksums and compares to checksums in the bundle MD5 file. The sequence of letters/numbers is identical, so bundle should pass validation.

## 📚 Version of Software Used
v2.0.7

## 🩺 Test Data / Additional context
[Bundle that encountered error](https://pds-geosciences.wustl.edu/mariner/mariner69/urn-nasa-pds-duxbury_pdart14_mariner69/)

##  🏞Screenshots
Example error message:
> ERROR  [error.label.checksum_mismatch]   Generated checksum '3cfdb8aa9203b216e0354b024ae6e083' does not match supplied checksum '3CFDB8AA9203B216E0354B024AE6E083' in the manifest for [file]

## 🖥 System Info
 - OS: 17763.1879
 - Version 1809

---

**Comment by qchaupds** [comment]
We made some good progress on finding where the issue.  After adding the following fix, the checksums do compare now.  Will check code in at next opportunity:

```
--- a/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
+++ b/src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileReferenceValidationRule.java
@@ -543,7 +543,11 @@ public class FileReferenceValidationRule extends AbstractValidationRule {
             String message = "";
             ProblemType type = null;
             ExceptionType severity = null;
-            if (!suppliedChecksum.equals(generatedChecksum)) {
+
+            LOG.debug("handleChecksum:urlRef " + urlRef + ",suppliedChecksum " + suppliedChecksum + ", generatedChecksum " + generatedChecksum);
+
+            // Note that the checksum can be uppercase or lowercase so the comparison should be case insensitive.
+            if (!suppliedChecksum.equalsIgnoreCase(generatedChecksum)) {
               message = "Generated checksum '" + generatedChecksum
                   + "' does not match supplied checksum '"
                   + suppliedChecksum + "' in the manifest for '"
```
