### ISSUE TITLE
Update rule documentation to remove "auto-detect" mention

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/validate#377]
## UPDATE
User story kept for documentation purposes, but see comments for task of updating `-R` help information.

---

## 💪 Motivation
The only condition that validate checks on the Bundle_Member_Entry class of the Bundle label is whether if at least one member is present. I believe it would be preferable that validate checks whether if all the members (collections) are specified in the bundle label o not. If not validate could raise an error (or at least a warning).

The DPH specifies the following: 

> The members of a bundle are specified using the Bundle_Member_Entry class. The Bundle_Member_Entry class is repeated for each collection product in the bundle.  This class must occur at least once in the Product_Bundle label

My understanding is that at least a Bundle has to have one member entry, but this does not imply that if more member entries are present, specifying one is enough. In fact later in the DPH one can read:

> You must use either the lid_reference or the lidvid_reference attribute for each member collection.

From that wording I understand that all the members must be present in the Bundle label.

## 📖 Additional Details

If I remove some of the members, validate does not throw an exception, but if I remove all of them, validate raises the following error:

ERROR  [error.label.schema]   line 5, 214: cvc-complex-type.2.4.b: The content of element 'Product_Bundle' is not complete. One of '{"http://pds.nasa.gov/pds4/pds/v1":Bundle_Member_Entry}' is expected.

## ⚖️ Acceptance Criteria
**Given** A bundle label
**When I perform** a validation
**Then I expect** an error if all bundle members are not specified with Bundle_Member_Entry classes.

**Comment by jordanpadams** [comment]
@mcostasitja if you run validate with with the flag `-R pds4.bundle` you should receive a warning when a collection exists in the directory structure, but is not referenced in the bundle.xml. is that not sufficient?

**Comment by mcostasitja** [comment]
@jordanpadams it is sufficient but, should not this be default behavior of the tool? 

For the -R parameter I read:

"Default is to auto-detect based on the contents at the location specified." 

so I would expect all the collections in the volume to be checked for.

**Comment by jordanpadams** [comment]
@mcostasitja we will update that documentation. the software no longer auto-detects baed on the contents because the number of use cases we came across for what could be in that directory has become unmanageable. Sorry of the lack of clarity there. the user must be explicit with the -R rule about what rule they want to check with.

**Comment by mcostasitja** [comment]
@jordanpadams OK with me and thanks!
