### ISSUE TITLE
validate raises an unexpected error with doi attribute in the Citation_information class

### ISSUE THREAD

**Issue by mcostasitja** [NASA-PDS/validate#378]
## 🐛 Describe the bug
Validate is providing the following error message when is not expected to:

> ERROR  [error.label.schema]   line 15, 12: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://pds.nasa.gov/pds4/pds/v1":doi}'. One of '{"http://pds.nasa.gov/pds4/pds/v1":keyword, "http://pds.nasa.gov/pds4/pds/v1":description}' is expected.

The doi attribute should appear before keyword and description attributes ([https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1G00.html#N-2006280352](https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1G00.html#N-2006280352)) and this is the way is provided in the label that is being validated:

    <Citation_Information>
       <author_list>Costa Sitja M.; Semenov B. V.</author_list>
       <publication_year>2021</publication_year>
       <doi>10.17189/1522402</doi>
       <keyword>Observation Geometry</keyword>
       <description>This bundle contains LADEE SPICE kernels and related documentation.</description>
     </Citation_Information>

## 📜 To Reproduce
Run validate with the provided label

## 🕵️ Expected behavior
I would not expect an error to be raised.

## 📚 Version of Software Used
gov.nasa.pds:validate
Version 2.0.6
Release Date: 2021-05-25 12:08:21

## 🩺 Test Data / Additional context
[bundle_ladee_spice_v001.txt](https://github.com/NASA-PDS/validate/files/6883778/bundle_ladee_spice_v001.txt)

## 🖥 System Info
 - OS: macOS Catalina 10.15.7 (19H1217)

---

**Comment by msbentley** [comment]
Hi @mcostasitja this looks like a bug in your label, not validate - the schematron is correctly defined, but the reference to the schema is to a waaay old version ("http://pds.nasa.gov/pds4/pds/v1 http://pds.nasa.gov/pds4/pds/v1/PDS4_PDS_1600.xsd")

**Comment by mcostasitja** [comment]
@msbentley ups! That's correct! It should be a G rather than a 6. 
@jordanpadams feel free the delete the issue.
