### ISSUE TITLE
Improve PDF/A validation to include more robust reporting on failures

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#388]
## 💪 Motivation
...so that I can know why my PDF is failing validation.

## 📖 Additional Details

Refs #382 where "supposed" PDF/A files are failing but the user does not know why. Let's output the verapdf report so folks can try to dissect it.

## ⚖️ Acceptance Criteria
**Given** PDS4 label `document.xml` referencing a PDF `document.pdf` that is not PDF/A compliant
**When I perform** validation with content validation enabled (default functionality)
**Then I expect** validate to fail when validating `document.xml` and the validation report should refer to a file on the file system where the verapdf validation report will be output.

## ⚙️ Engineering Details

- [x] update software to output verapdf report to file on file system (make sure it is OS agnostic)
- [x] update validate documentation:
    - [x] new section noting we are validating PDF/A
    - [x] note that we are using verapdf with link to the website
    - [x] note that the referenced output reports are directly from verapdf. for more information on what PDF/A-1A conformance really means, see [PDFA.org documentation](https://www.pdfa.org/accessibility-what-pdf-a-1a-really-means/)

**Comment by qchaupds** [comment]
Can confirm that the following validate run produces the invalid message for the PDF file.  Will work on extracting the report from the third party software to an external file:

```
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 137 % validate -R pds4.label -r report_github388_label_invalid.json  -s json -t src/test/resources/github388/pixl_edr_sis_bad.xml  >& t1

{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 139 % grep message  report_github388_label_invalid.json 
      "messages": [
          "message": "file:/home/qchau/sandbox/validate/src/test/resources/github388/pixl_edr_sis_bad.pdf is not valid PDF/A file or does not exist"
    "messageTypes": [
        "messageType": "warning.pdf.file.not_pdfa_compliant",
```

**Comment by tloubrieu-jpl** [comment]
there is an email thread on-going, @qchaupds is waiting for @jordanpadams executive decision.

**Comment by jpl-jengelke** [comment]
[testdata.zip](https://github.com/NASA-PDS/validate/files/8674013/testdata.zip)
