### ISSUE TITLE
Perform benchmarking on validate to enable documenting of system requirements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#41]
Provide metrics for the following:

1) Rough estimate of timing needed per label-validated product
2) Rough estimate of time needed per content-validated product
2) Timing differences of content validation, based on size of input.  For example a small image vs. a large image (e.g. a mosaic)

End users can use these metrics to gauge necessary time/hardware.
PDS EN can use these metrics to regression test future versions of the code, to make sure performance doesn't degrade.

**Comment by jordanpadams** [comment]
When running validate against the imagecube in https://starbase.jpl.nasa.gov/pds4/1900/dph_examples_v1900.zip:

```
validate-1.16.0-SNAPSHOT/bin/validate ~/Downloads/V1900/dph_example_archive/data_imagecube/virs/H01/virs_cube_64ppd_h01np.xml
```
Image ~4.8GiB, took ~71 minutes (4276 seconds), Max Heap 3,757,047,808 B (from VisualVM on Mac)
<img width="483" alt="Screen Shot 2019-07-26 at 6 34 56 AM" src="https://user-images.githubusercontent.com/33492486/61955288-88088080-af6f-11e9-96e7-ef96213dc756.png">

**Comment by galenatjpl** [comment]
A small img file (~253K) takes about 16 seconds to validate.
time ../../target/validate-*/bin/validate ./temp/V1900/dph_example_archive/data_tnmap/thermal_neutron_map.xml
<img width="1713" alt="Screen Shot 2019-09-09 at 10 46 50 AM" src="https://user-images.githubusercontent.com/47542238/64553981-56fdc880-d2ef-11e9-90d6-7e14df112db6.png">

**Comment by galenatjpl** [comment]
Large (~4.8GB) file (with --no-data-check flag) took ~29 seconds.
time ../../target/validate-*/bin/validate --no-data-check ./temp/V1900/dph_example_archive/data_imagecube/virs/H01/virs_cube_64ppd_h01np.xml
<img width="1713" alt="Screen Shot 2019-09-09 at 10 46 50 AM" src="https://user-images.githubusercontent.com/47542238/64566597-30e62180-d30b-11e9-9b11-d5c961016ac1.png">

**Comment by galenatjpl** [comment]
I think in summary, we can word our system requirements like this:

Memory Requirements:
 * Absolute minumum 4GB
 * If doing content-validation, then you will need more than the size your largest data file

Timing Requirements:
 * When not doing data checking:  Typically under 30 seconds per file validation
 * When doing data check, it depends on the data size:
   * ~253K = 16 seconds
   * ~4.8GB = 101 minutes
