### ISSUE TITLE
Scaled value min/max error does not display scaled value

### ISSUE THREAD

**Issue by jstone-psi** [NASA-PDS/validate#434]
## 🐛 Describe the bug
When validating an image that has a scaled value that is out of range, the error message displays the unscaled value, instead of the scaled value, which is confusing and misleading.

## 📜 To Reproduce
Run the validator on the included label:

```
validate st_2480739249_v.xml
```

## 🕵️ Expected behavior
The error message should display the scaled value (-128.0) instead of the unscaled value (0) in the error message. So the correct error message would be

> `      ERROR  [error.array.value_out_of_scaled_min_max_range]   array 1, location (1, 1): Scaled value is less than the scaled minimum value in the label (min=-126.0, got=-128.0).`

instead of

> `      ERROR  [error.array.value_out_of_scaled_min_max_range]   array 1, location (1, 1): Scaled value is less than the scaled minimum value in the label (min=-126.0, got=0).
`

## 📚 Version of Software Used
validate 2.1.0

## 🩺 Test Data / Additional context

[st_2480739249_v.zip](https://github.com/NASA-PDS/validate/files/7437197/st_2480739249_v.zip)

## 🖥 System Info
 - OS: MacOS Big Sur
 - Java: openjdk 17

---

**Comment by jstone-psi** [comment]
I accidentally ran this on 2.0.7 in the attached report. Here's another error log that shows it running on 2.1.0.

[st_2480739249_v.txt](https://github.com/NASA-PDS/validate/files/7437703/st_2480739249_v.txt)

**Comment by jordanpadams** [comment]
closed per #514 and #529
