### ISSUE TITLE
Improve file base name check according to Standards Reference

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#5]
Bob Deen [4:35 PM]
hey @Michael Cayanan what's with this error:
```FAIL: file:/home/nsytmipl/algermis/nsyt_archive_pipeline/bundle_workspace/insight_cameras/miscellaneous/core.vmac
ERROR [error.file.unallowed_base_name] File base name is not allowed```

what base name is not allowed and why?

 

Cristina De Cesare [4:37 PM]
we just need help with basename (edited) 
delete the message
so @Michael Cayanan can see the other stuff
ty ty

Michael Cayanan [4:37 PM]
let me check…

Cristina De Cesare [4:37 PM]
thanks! I have never encountered this one before

Michael Cayanan [4:39 PM]
So `core` is a prohibited base name according to section 6C.1.2 of the PDS4 Standards: https://pds.nasa.gov/datastandards/documents/sr/current/StdRef_1.11.0.pdf

Bob Deen [4:40 PM]
it's not core it's core.vmac
not the same file
i understand not wanting core but core.vmac is completely different
so the validation error is invalid because the standard says that's a prohibited filename not a prohibited basename

Michael Cayanan [4:44 PM]
That check was put in place by the developer before I took over it. This is one of those things that needs to be brought to attention at a monthly PDS Tool Working Group meeting, where @Galen Hollins can bring this up and ask for Node consensus on this issue

**Comment by qchaupds** [comment]
The bug is this line in src/main/java/gov/nasa/pds/tools/validate/rule/pds4/FileAndDirectoryNamingRule.java

`if (PROHIBITED_BASE_NAMES.contains(baseName))`

The variable baseName is the name of the file without the extension.

A better check would be to check the whole name (baseName plus extension)

`if (PROHIBITED_BASE_NAMES.contains(name))`

so the following would then be true:

       -    'core' should not be valid
       -     'core.vmac' should be valid
       -     'lpt8' should not be valid
       -    'com4' should not be valid
       -     'file_aux_should_be_ok.tab' should be valid
       -     'lpt9.tab' should be valid
       -   'lpt9_should_be_ok.tab' should be valid
       -     'this_file_should_be_ok_core.tab' should be valid
