### ISSUE TITLE
Add new target-manifest flag for user to provide a manifest (file) of file/directory paths to validate

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#50]
Current `--target` flag supports the ability to specify a set of files/directories to validate.

Create a new flag that allows for a `target-manifest` to be specified that contains a list of files/directories to validate.

**Comment by danyu-pds** [comment]
@jordanpadams @galenatjpl 
Dose the milestone change to PDS.26 (was changed 14days ago) from PDS.25 (was added 22days ago)?  

What is the different between "a set of files/directories to validate." and "a list of files/directories to validate"?

Do you have a example file of manifest (file)?

**Comment by jordanpadams** [comment]
@danyu-pds I don't have one off-hand, but you can think of it as a file containing a list of files/directories separated by newlines, e.g.

```
/path/to/file/a.xml
/path/to/file/b.xml
/path/to/file/c.xml
/path/to/file/d.xml
/path/to/file/e.xml
```

**Comment by danyu-pds** [comment]
> @danyu-pds I don't have one off-hand, but you can think of it as a file containing a list of files/directories separated by newlines, e.g.
> 
> ```
> /path/to/file/a.xml
> /path/to/file/b.xml
> /path/to/file/c.xml
> /path/to/file/d.xml
> /path/to/file/e.xml
> ```

OK. Will do.

**Comment by danyu-pds** [comment]
Added new option "--target-list-file" for the command line and
"validate.targetListFile" for the config file.

Modified index.xml.vm for the new option.

To test:
bin/validate -c [config file]
bin/validate --target-list-file [target list file] -t [target file]
bin/validate --target-list-file [target list file] 

Check the target files in the report (Parameters:Targets).
