### ISSUE TITLE
Validate that Table_Character/Table_Binary fields match the field length definitions in the label

### ISSUE THREAD

**Issue by msbentley** [NASA-PDS/validate#56]
**Is your feature request related to a problem? Please describe.**
Currently, validate does not report when the definition of two fields in a Table_Character overlap. This is a relatively common error by data producers, and should be easy to flag.

**Describe the solution you'd like**
validate should report an error if fields overlap

**Comment by jordanpadams** [comment]
@msbentley do you have a product we could use for testing?

**Comment by msbentley** [comment]
I've just created a (rather silly, admittedly) example product: [validate_test_fields.zip](https://github.com/NASA-PDS-Incubator/validate/files/3530632/validate_test_fields.zip)

Two of the numeric fields here overlap. The product validates and indeed opens without error, but I can't think of a use case where this would be valid, but perhaps that's my lack of imagination (i.e. I'm not sure if this should be a warning or should fail validation...)

**Comment by hhlee445** [comment]
Added error message when the definition of two fields in a Table_Character overlap.

`Begin Content Validation: file:/Users/hyunlee/dev/pds_en/validate/issue_56/validate_test_fields/minimal_test_product.tab
      ERROR  [error.table.field_value_overlap]   table 1, record 1, field 3: The field is overlapping with the next field. Current field ends at 45. Next field starts at 43
      ERROR  [error.table.field_value_overlap]   table 1, record 2, field 3: The field is overlapping with the next field. Current field ends at 45. Next field starts at 43
      ERROR  [error.table.field_value_overlap]   table 1, record 3, field 3: The field is overlapping with the next field. Current field ends at 45. Next field starts at 43
      ERROR  [error.table.field_value_overlap]   table 1, record 4, field 3: The field is overlapping with the next field. Current field ends at 45. Next field starts at 43`

**Comment by msbentley** [comment]
I assume the same check should be applied to Table_Binary?

**Comment by jordanpadams** [comment]
@msbentley correct. do you by any chance have an example? if not, we can poke around.

**Comment by msbentley** [comment]
For Table_Binary? No, but I could take my Table_Character example and change it to binary, if you can't find anything else...

**Comment by jordanpadams** [comment]
thanks @msbentley we will ping you if we need it but we can probably do the conversion as well.
