### ISSUE TITLE
Investigate and determine potential content validation performance improvements

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#78]
Use some of the benchmarking metrics from #41, and dig through the code to see where we may be able to improve performance in content validation.

**Comment by galenatjpl** [comment]
As a related data point, here's a chart showing the performance when --spot-check-data is applied at various levels.
<img width="354" alt="Screen Shot 2019-09-11 at 10 14 06 AM" src="https://user-images.githubusercontent.com/47542238/64720303-00bf8f80-d47f-11e9-92bf-f234420645a7.png">
You can see that it's "roughly" doubling in time as the flag value is halved.

**Comment by jordanpadams** [comment]
Closed per implementation completed for #30
