### ISSUE TITLE
Validate and throw error when duplicate LIDs are found in Bundle

### ISSUE THREAD

**Issue by galenatjpl** [NASA-PDS/validate#81]
From Ron Joiner:

Howdy,
 
I ran validate against a Bundle that mistakenly had duplicate product LIDs – which is a big No No.  It would be nice if validate checked and reported any duplicates:
 
   <Identification_Area>
        <logical_identifier>urn:nasa:pds:excalibur:data</logical_identifier>

 
RJ

**Comment by qchaupds** [comment]
The current code already check for duplicate identifier:


validate -R pds4.bundle --skip-context-validation --skip-content-validation -r report_github81_invalid.json -s json -t src/test/resources/github81/invalid/bundle
_kaguya_derived.xml
{pds-dev3.jpl.nasa.gov}/home/qchau/sandbox/validate 109 % egrep "status|label" report_github81_invalid.json
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github81/invalid/data_spectra/kgrs_calibrated_spectra_per1.xml",
      "status": "FAIL",
      "label": "file:/home/qchau/sandbox/validate/src/test/resources/github81/invalid/data_spectra/kgrs_calibrated_spectra_per2.xml",
          "type": "error.label.duplicate_identifier",

Jordan suggest this test be added to regression tests.

**Comment by jordanpadams** [comment]
Closing per comment above.
