### ISSUE TITLE
Update content validation to fail when the value of an ASCII_Integer is all spaces

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/validate#9]
When validating the attached, if you run as follows:

```
./validate -v 0 -f ../../whitespace_test/minimal_test_product_bad.xml
```
One of the info messages is:

```
INFO  [info.table.blank_field_value]   table 1, record 2, field 2: Field is blank.
Record 2 is an ASCII_Integer, but the value is a "space" character (ASCII 0x20) which is not a valid ASCII_Integer. This should be an ERROR not an INFO.
```

**Comment by jordanpadams** [comment]
Test products attached. Note: aaaTest label should be used as an example to create a minimal_test_product_success.xml label where it will use special constants to allow for a blank field.

[test_data.zip](https://github.com/NASA-PDS-Incubator/pds4-validate-tool/files/3322226/test_data.zip)

**Comment by msbentley** [comment]
I've just noticed that this issue also affects the ASCII_Real data type - I get the same problem (validation passes, but when I switch to verbosity 1 I get a stream of "Field is blank" INFO level messages, but the product is essentially invalid).

Possibly it affects all numeric types?

**Comment by jordanpadams** [comment]
De-scoped to work on AIP/SIP Generation software

**Comment by hhlee445** [comment]
Added github9 test case into regression test.

**Comment by rchenatjpl** [comment]
I would change the title of this issue from
"Update content validation to fail when a space character is used when an ASCII_Integer type is specified" to
"Update content validation to fail when the value of an ASCII_Integer is all spaces"
because validate v1.17 allows leading and/or trailing spaces. Actually, I want to verify that that is the desired behavior.

**Comment by jordanpadams** [comment]
@rchenatjpl that is correct. according to the SR and PDS DSV standard, leading and trailing whitespace are ok.

**Comment by rchenatjpl** [comment]
What's the final answer - should validate throw or not throw an error for an all-blank ASCII_Integer? My validate throws errors:
    Begin Content Validation: file:/Users/rchen/Desktop/test/testPrep/val9.tab
      ERROR  [error.table.field_value_data_type_mismatch]   table 1, record 1, field 2: Value does not match its data type 'ASCII_Integer': '   ' does not match the pattern '[+-]?\d+'
      ERROR  [error.table.field_value_data_type_mismatch]   table 1, record 2, field 2: Value does not match its data type 'ASCII_Integer': '   ' does not match the pattern '[+-]?\d+'
    End Content Validation: file:/Users/rchen/Desktop/test/testPrep/val9.tab
        1 product validation(s) completed

**Comment by jordanpadams** [comment]
@rchenatjpl invalid for a delimited table (PDS DSV), valid for a character table.

**Comment by rchenatjpl** [comment]
Thanks, Jordan. Validate v1.22.1 throws an error for both Table_Character and Table_Delimited. pds4_viewer chokes on Table_Character but displays Table_Delimited correctly.
[Archive.zip](https://github.com/NASA-PDS-Incubator/validate/files/4422476/Archive.zip)
