### ISSUE TITLE
Number of fields in CSV file not being counted correctly 

### ISSUE THREAD

**Issue by aywaldron** [NASA-PDS/validate#96]
**Describe the bug**
We have CSVs files with header rows that looks like this:
```
#time(s)       , elapsed_time(hr), enc1(rad), enc2(rad), enc3(rad), enc4(rad), pot1(rad), pot2(rad), pot3(rad), pot4(rad), tcase1(C), tcase2(C), tcase3(C), tcase4(C), trotor1(C), trotor2(C), trotor3(C), trotor4(C), tgrapple(C), cur1(mA), cur2(mA), cur3(mA), cur4(mA), volt1(V), volt2(V), volt3(V), volt4(V), stat  , tool  , x_enc(m), y_enc(m), z_enc(m), th_enc(m), x_pot(m), y_pot(m), z_pot(m), th_pot(m), x_enc_defl(m), y_enc_defl(m), z_enc_defl(m), th_enc_defl(m), x_pot_defl(m), y_pot_defl(m), z_pot_defl(m), th_pot_defl(m), v1(rad/s), v2(rad/s), v3(rad/s), v4(rad/s), tau1(N-m), tau2(N-m), tau3(N-m), tau4(N-m), Fr(N)      , Ft(N)      , Fz(N)      , htr_cur(mA), grapple_phase
```
Manual inspection, reading the file into standard Python libraries, and our data source all tell us that there are 58 fields. However validate counts 57 fields. If I remove the extra spaces from this row, validate counts 55 fields. If we remove the `#` at the beginning of the line, it still counts 57 fields.

**To Reproduce**
1. Open the attached zip which contains the CSV file and its PDS4 label.
[examples.zip](https://github.com/NASA-PDS-Incubator/validate/files/3610909/examples.zip)
2. Run validate 1.15.3 or 1.15.0 on the attached label.

**Expected behavior**
The error is not thrown because validate counts 58 fields in the CSV file.

**Version of Software Used**
1.15.3, 1.15.0

**Screenshots**
<img width="862" alt="Screen Shot 2019-09-13 at 9 36 46 AM" src="https://user-images.githubusercontent.com/42559100/64879103-0dbcba00-d60a-11e9-8df8-f0f288051837.png">

**Desktop (please complete the following information):**
 - OS: Occured on Fedora 7.3 and OSX 10.14

**Comment by jordanpadams** [comment]
@aywaldron looking at this now.

btw, after running with the latest SNAPSHOT of validate, I can tell you the "name" used in the Observing_System_Component for the InSight spacecraft is invalid. The context product for InSight says "InSight", but your label says "InSight Lander". Either the context product or your label should be updated accordingly (note: this is a new feature being added to validate with this next build).

**Comment by jordanpadams** [comment]
@aywaldron the error is in the offset specified in the label. current offset is set to 700 but this pushes validate to start in the next row, missing the first field. this should really be set to 678. when I change those values, it works like a charm :-)

```
    <Header>
      <offset unit="byte">0</offset>
      <object_length unit="byte">678</object_length>
      <parsing_standard_id>7-Bit ASCII Text</parsing_standard_id>
      <description>Column headings</description>
    </Header>
    <Table_Delimited>
      <local_identifier>TABLE</local_identifier>
      <offset unit="byte">678</offset>
      <parsing_standard_id>PDS DSV 1</parsing_standard_id>
      <records>147</records>
      <record_delimiter>Carriage-Return Line-Feed</record_delimiter>
      <field_delimiter>Comma</field_delimiter>
```

That being said, we do need a "error message decoder ring" so folks know how to debug these error messages.  I will update our docs and the code to direct people to it now.

**Comment by TheOneTrueCDC** [comment]
Thanks @jordanpadams ! I will make this change and re-try.

**Comment by jordanpadams** [comment]
Closing per #97 for documentation updates
